CREATE TABLE `familysize` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `NameEn` varchar(255) DEFAULT NULL COMMENT '名称',
  `NameCn` varchar(255) DEFAULT NULL COMMENT '名称',
  `BodyType` varchar(20) DEFAULT NULL COMMENT '服装形体',
  `Height` double DEFAULT NULL COMMENT '身高',
  `Weight` double DEFAULT NULL COMMENT '体重',
  `ShoulderSize` double DEFAULT NULL COMMENT '肩宽cm',
  `BustSzie` double DEFAULT NULL COMMENT '胸围cm',
  `WaistSize` double DEFAULT NULL COMMENT '腰围cm',
  `Hipline` double DEFAULT NULL COMMENT '臀围',
  `ShoesSize` varchar(20) DEFAULT NULL COMMENT '鞋子尺码',
  `SizeObj` varchar(255) DEFAULT NULL COMMENT '其它参数 {}',
  `UserIdFk` bigint(20) DEFAULT NULL COMMENT '用户Id',
  `Idx` int(11) DEFAULT NULL,
  `WebUrls` varchar(255) DEFAULT NULL,
  `AdsIds_fk` varchar(255) DEFAULT NULL,
  `Status` int(11) DEFAULT '0' COMMENT '删除状态',
  `Remarks` varchar(255) DEFAULT '厘米数×2－10=欧制 （欧制+10）÷2=厘米数　　厘米数－18+0.5=美制 美制+18－0.5=厘米数　　厘米数－18－0.5=英制 英制+18+0.5=厘米数' COMMENT '备注',
  `CreateTime` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `CreateBy` varchar(255) DEFAULT NULL,
  `UpdateTime` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `UpdateBy` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4;