CREATE TABLE `wo_timestable` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `start_time` int(11) DEFAULT '0' COMMENT 'int开始时间',
  `start_time_string` varchar(255) DEFAULT NULL COMMENT '开始时间串',
  `start_time_date` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '日期',
  `day_start` int(11) DEFAULT NULL COMMENT '一天的开始时间int',
  `day_start_string` varchar(255) DEFAULT NULL COMMENT '一天的开始时间串',
  `start_day_key` varchar(10) DEFAULT NULL COMMENT 'daykey yyyy-MM-dd',
  `end_time` int(11) DEFAULT '0' COMMENT 'int结束时间',
  `end_time_string` varchar(255) DEFAULT NULL COMMENT '结束时间串',
  `end_time_date` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '日期',
  `start_day_end` int(11) DEFAULT NULL COMMENT '开始时间当天结束的23.59.59秒的int',
  `start_day_end_string` varchar(255) DEFAULT NULL COMMENT '开始时间当天结束的23.59.59秒的时间串',
  `end_day_key` varchar(10) DEFAULT NULL COMMENT 'daykey yyyy-MM-dd',
  `time_zone` int(11) DEFAULT '0' COMMENT '时区数字',
  `time_zone_etc` varchar(255) DEFAULT 'Etc/GMT+0' COMMENT '时区ETC',
  `time_zone_gmt` varchar(255) DEFAULT 'GMT+00:00' COMMENT '时区GMT',
  `duration_start_day` int(11) DEFAULT '0' COMMENT '属于前一天的时间(分钟)',
  `duration_end_day` int(11) DEFAULT '0' COMMENT '属于后一天的时间(分钟)',
  `duration_total` int(11) DEFAULT NULL,
  `tel` varchar(255) DEFAULT NULL,
  `tel_prefix` varchar(255) DEFAULT NULL,
  `country` varchar(255) DEFAULT NULL COMMENT '国家',
  `country_code` varchar(255) DEFAULT NULL COMMENT '国家码',
  `language` varchar(255) DEFAULT NULL COMMENT '语言',
  `ip` varchar(255) DEFAULT NULL COMMENT 'ip',
  `create_time` int(11) DEFAULT NULL COMMENT '创建时间int',
  `update_time` int(11) DEFAULT NULL COMMENT '更新时间int',
  `user_id` bigint(20) DEFAULT NULL COMMENT '用户Id',
  `content_obj` varchar(255) DEFAULT NULL COMMENT '主要内容',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=535 DEFAULT CHARSET=utf8mb4;

