package com.gafker.manage.entity;

import java.util.Date;

public class Familygeneration {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.id
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.UstringId
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private String ustringid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.NameEn
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private String nameen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.NameCn
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private String namecn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.AncestryName
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private String ancestryname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.Generation
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private String generation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.AncestryUse
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private Integer ancestryuse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.Idx
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private Integer idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.Qrcode
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private String qrcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.FamilyNames_fk
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private Long familynamesFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.WebUrls
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private String weburls;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.AdsIds__fk
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private String adsidsFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.GenerationParentId
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private Long generationparentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.Branch
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private Integer branch;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.SubBranch
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private Integer subbranch;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.ReGenerationTime
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private Integer regenerationtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.PersonArea
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private String personarea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.LeaderId
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private Long leaderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.TotalPerson
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private Long totalperson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.UpdateBy
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private Long updateby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.UpdateTime
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private Date updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.CreateBy
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private Long createby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.CreateTime
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familygeneration.DelFlag
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	private Integer delflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.id
	 * @return  the value of familygeneration.id
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.id
	 * @param id  the value for familygeneration.id
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.UstringId
	 * @return  the value of familygeneration.UstringId
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public String getUstringid() {
		return ustringid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.UstringId
	 * @param ustringid  the value for familygeneration.UstringId
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setUstringid(String ustringid) {
		this.ustringid = ustringid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.NameEn
	 * @return  the value of familygeneration.NameEn
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public String getNameen() {
		return nameen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.NameEn
	 * @param nameen  the value for familygeneration.NameEn
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setNameen(String nameen) {
		this.nameen = nameen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.NameCn
	 * @return  the value of familygeneration.NameCn
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public String getNamecn() {
		return namecn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.NameCn
	 * @param namecn  the value for familygeneration.NameCn
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setNamecn(String namecn) {
		this.namecn = namecn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.AncestryName
	 * @return  the value of familygeneration.AncestryName
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public String getAncestryname() {
		return ancestryname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.AncestryName
	 * @param ancestryname  the value for familygeneration.AncestryName
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setAncestryname(String ancestryname) {
		this.ancestryname = ancestryname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.Generation
	 * @return  the value of familygeneration.Generation
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public String getGeneration() {
		return generation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.Generation
	 * @param generation  the value for familygeneration.Generation
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setGeneration(String generation) {
		this.generation = generation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.AncestryUse
	 * @return  the value of familygeneration.AncestryUse
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public Integer getAncestryuse() {
		return ancestryuse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.AncestryUse
	 * @param ancestryuse  the value for familygeneration.AncestryUse
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setAncestryuse(Integer ancestryuse) {
		this.ancestryuse = ancestryuse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.Idx
	 * @return  the value of familygeneration.Idx
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public Integer getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.Idx
	 * @param idx  the value for familygeneration.Idx
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.Qrcode
	 * @return  the value of familygeneration.Qrcode
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public String getQrcode() {
		return qrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.Qrcode
	 * @param qrcode  the value for familygeneration.Qrcode
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setQrcode(String qrcode) {
		this.qrcode = qrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.FamilyNames_fk
	 * @return  the value of familygeneration.FamilyNames_fk
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public Long getFamilynamesFk() {
		return familynamesFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.FamilyNames_fk
	 * @param familynamesFk  the value for familygeneration.FamilyNames_fk
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setFamilynamesFk(Long familynamesFk) {
		this.familynamesFk = familynamesFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.WebUrls
	 * @return  the value of familygeneration.WebUrls
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public String getWeburls() {
		return weburls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.WebUrls
	 * @param weburls  the value for familygeneration.WebUrls
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setWeburls(String weburls) {
		this.weburls = weburls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.AdsIds__fk
	 * @return  the value of familygeneration.AdsIds__fk
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public String getAdsidsFk() {
		return adsidsFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.AdsIds__fk
	 * @param adsidsFk  the value for familygeneration.AdsIds__fk
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setAdsidsFk(String adsidsFk) {
		this.adsidsFk = adsidsFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.GenerationParentId
	 * @return  the value of familygeneration.GenerationParentId
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public Long getGenerationparentid() {
		return generationparentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.GenerationParentId
	 * @param generationparentid  the value for familygeneration.GenerationParentId
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setGenerationparentid(Long generationparentid) {
		this.generationparentid = generationparentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.Branch
	 * @return  the value of familygeneration.Branch
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public Integer getBranch() {
		return branch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.Branch
	 * @param branch  the value for familygeneration.Branch
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setBranch(Integer branch) {
		this.branch = branch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.SubBranch
	 * @return  the value of familygeneration.SubBranch
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public Integer getSubbranch() {
		return subbranch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.SubBranch
	 * @param subbranch  the value for familygeneration.SubBranch
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setSubbranch(Integer subbranch) {
		this.subbranch = subbranch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.ReGenerationTime
	 * @return  the value of familygeneration.ReGenerationTime
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public Integer getRegenerationtime() {
		return regenerationtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.ReGenerationTime
	 * @param regenerationtime  the value for familygeneration.ReGenerationTime
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setRegenerationtime(Integer regenerationtime) {
		this.regenerationtime = regenerationtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.PersonArea
	 * @return  the value of familygeneration.PersonArea
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public String getPersonarea() {
		return personarea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.PersonArea
	 * @param personarea  the value for familygeneration.PersonArea
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setPersonarea(String personarea) {
		this.personarea = personarea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.LeaderId
	 * @return  the value of familygeneration.LeaderId
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public Long getLeaderid() {
		return leaderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.LeaderId
	 * @param leaderid  the value for familygeneration.LeaderId
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setLeaderid(Long leaderid) {
		this.leaderid = leaderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.TotalPerson
	 * @return  the value of familygeneration.TotalPerson
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public Long getTotalperson() {
		return totalperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.TotalPerson
	 * @param totalperson  the value for familygeneration.TotalPerson
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setTotalperson(Long totalperson) {
		this.totalperson = totalperson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.UpdateBy
	 * @return  the value of familygeneration.UpdateBy
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public Long getUpdateby() {
		return updateby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.UpdateBy
	 * @param updateby  the value for familygeneration.UpdateBy
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setUpdateby(Long updateby) {
		this.updateby = updateby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.UpdateTime
	 * @return  the value of familygeneration.UpdateTime
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.UpdateTime
	 * @param updatetime  the value for familygeneration.UpdateTime
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.CreateBy
	 * @return  the value of familygeneration.CreateBy
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public Long getCreateby() {
		return createby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.CreateBy
	 * @param createby  the value for familygeneration.CreateBy
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setCreateby(Long createby) {
		this.createby = createby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.CreateTime
	 * @return  the value of familygeneration.CreateTime
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.CreateTime
	 * @param createtime  the value for familygeneration.CreateTime
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familygeneration.DelFlag
	 * @return  the value of familygeneration.DelFlag
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public Integer getDelflag() {
		return delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familygeneration.DelFlag
	 * @param delflag  the value for familygeneration.DelFlag
	 * @mbggenerated  Fri Feb 24 23:17:29 CST 2017
	 */
	public void setDelflag(Integer delflag) {
		this.delflag = delflag;
	}
}