package com.gafker.manage.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FamilytraceabilityExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public FamilytraceabilityExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUstringidIsNull() {
			addCriterion("UstringId is null");
			return (Criteria) this;
		}

		public Criteria andUstringidIsNotNull() {
			addCriterion("UstringId is not null");
			return (Criteria) this;
		}

		public Criteria andUstringidEqualTo(String value) {
			addCriterion("UstringId =", value, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidNotEqualTo(String value) {
			addCriterion("UstringId <>", value, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidGreaterThan(String value) {
			addCriterion("UstringId >", value, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidGreaterThanOrEqualTo(String value) {
			addCriterion("UstringId >=", value, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidLessThan(String value) {
			addCriterion("UstringId <", value, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidLessThanOrEqualTo(String value) {
			addCriterion("UstringId <=", value, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidLike(String value) {
			addCriterion("UstringId like", value, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidNotLike(String value) {
			addCriterion("UstringId not like", value, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidIn(List<String> values) {
			addCriterion("UstringId in", values, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidNotIn(List<String> values) {
			addCriterion("UstringId not in", values, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidBetween(String value1, String value2) {
			addCriterion("UstringId between", value1, value2, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidNotBetween(String value1, String value2) {
			addCriterion("UstringId not between", value1, value2, "ustringid");
			return (Criteria) this;
		}

		public Criteria andNameenIsNull() {
			addCriterion("NameEn is null");
			return (Criteria) this;
		}

		public Criteria andNameenIsNotNull() {
			addCriterion("NameEn is not null");
			return (Criteria) this;
		}

		public Criteria andNameenEqualTo(String value) {
			addCriterion("NameEn =", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenNotEqualTo(String value) {
			addCriterion("NameEn <>", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenGreaterThan(String value) {
			addCriterion("NameEn >", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenGreaterThanOrEqualTo(String value) {
			addCriterion("NameEn >=", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenLessThan(String value) {
			addCriterion("NameEn <", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenLessThanOrEqualTo(String value) {
			addCriterion("NameEn <=", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenLike(String value) {
			addCriterion("NameEn like", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenNotLike(String value) {
			addCriterion("NameEn not like", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenIn(List<String> values) {
			addCriterion("NameEn in", values, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenNotIn(List<String> values) {
			addCriterion("NameEn not in", values, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenBetween(String value1, String value2) {
			addCriterion("NameEn between", value1, value2, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenNotBetween(String value1, String value2) {
			addCriterion("NameEn not between", value1, value2, "nameen");
			return (Criteria) this;
		}

		public Criteria andNamecnIsNull() {
			addCriterion("NameCn is null");
			return (Criteria) this;
		}

		public Criteria andNamecnIsNotNull() {
			addCriterion("NameCn is not null");
			return (Criteria) this;
		}

		public Criteria andNamecnEqualTo(String value) {
			addCriterion("NameCn =", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnNotEqualTo(String value) {
			addCriterion("NameCn <>", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnGreaterThan(String value) {
			addCriterion("NameCn >", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnGreaterThanOrEqualTo(String value) {
			addCriterion("NameCn >=", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnLessThan(String value) {
			addCriterion("NameCn <", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnLessThanOrEqualTo(String value) {
			addCriterion("NameCn <=", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnLike(String value) {
			addCriterion("NameCn like", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnNotLike(String value) {
			addCriterion("NameCn not like", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnIn(List<String> values) {
			addCriterion("NameCn in", values, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnNotIn(List<String> values) {
			addCriterion("NameCn not in", values, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnBetween(String value1, String value2) {
			addCriterion("NameCn between", value1, value2, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnNotBetween(String value1, String value2) {
			addCriterion("NameCn not between", value1, value2, "namecn");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("Title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("Title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("Title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("Title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("Title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("Title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("Title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("Title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("Title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("Title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("Title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("Title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("Title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("Title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andStepIsNull() {
			addCriterion("Step is null");
			return (Criteria) this;
		}

		public Criteria andStepIsNotNull() {
			addCriterion("Step is not null");
			return (Criteria) this;
		}

		public Criteria andStepEqualTo(Integer value) {
			addCriterion("Step =", value, "step");
			return (Criteria) this;
		}

		public Criteria andStepNotEqualTo(Integer value) {
			addCriterion("Step <>", value, "step");
			return (Criteria) this;
		}

		public Criteria andStepGreaterThan(Integer value) {
			addCriterion("Step >", value, "step");
			return (Criteria) this;
		}

		public Criteria andStepGreaterThanOrEqualTo(Integer value) {
			addCriterion("Step >=", value, "step");
			return (Criteria) this;
		}

		public Criteria andStepLessThan(Integer value) {
			addCriterion("Step <", value, "step");
			return (Criteria) this;
		}

		public Criteria andStepLessThanOrEqualTo(Integer value) {
			addCriterion("Step <=", value, "step");
			return (Criteria) this;
		}

		public Criteria andStepIn(List<Integer> values) {
			addCriterion("Step in", values, "step");
			return (Criteria) this;
		}

		public Criteria andStepNotIn(List<Integer> values) {
			addCriterion("Step not in", values, "step");
			return (Criteria) this;
		}

		public Criteria andStepBetween(Integer value1, Integer value2) {
			addCriterion("Step between", value1, value2, "step");
			return (Criteria) this;
		}

		public Criteria andStepNotBetween(Integer value1, Integer value2) {
			addCriterion("Step not between", value1, value2, "step");
			return (Criteria) this;
		}

		public Criteria andIdxIsNull() {
			addCriterion("Idx is null");
			return (Criteria) this;
		}

		public Criteria andIdxIsNotNull() {
			addCriterion("Idx is not null");
			return (Criteria) this;
		}

		public Criteria andIdxEqualTo(Integer value) {
			addCriterion("Idx =", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxNotEqualTo(Integer value) {
			addCriterion("Idx <>", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxGreaterThan(Integer value) {
			addCriterion("Idx >", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxGreaterThanOrEqualTo(Integer value) {
			addCriterion("Idx >=", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxLessThan(Integer value) {
			addCriterion("Idx <", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxLessThanOrEqualTo(Integer value) {
			addCriterion("Idx <=", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxIn(List<Integer> values) {
			addCriterion("Idx in", values, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxNotIn(List<Integer> values) {
			addCriterion("Idx not in", values, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxBetween(Integer value1, Integer value2) {
			addCriterion("Idx between", value1, value2, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxNotBetween(Integer value1, Integer value2) {
			addCriterion("Idx not between", value1, value2, "idx");
			return (Criteria) this;
		}

		public Criteria andWeburlsIsNull() {
			addCriterion("WebUrls is null");
			return (Criteria) this;
		}

		public Criteria andWeburlsIsNotNull() {
			addCriterion("WebUrls is not null");
			return (Criteria) this;
		}

		public Criteria andWeburlsEqualTo(String value) {
			addCriterion("WebUrls =", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsNotEqualTo(String value) {
			addCriterion("WebUrls <>", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsGreaterThan(String value) {
			addCriterion("WebUrls >", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsGreaterThanOrEqualTo(String value) {
			addCriterion("WebUrls >=", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsLessThan(String value) {
			addCriterion("WebUrls <", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsLessThanOrEqualTo(String value) {
			addCriterion("WebUrls <=", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsLike(String value) {
			addCriterion("WebUrls like", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsNotLike(String value) {
			addCriterion("WebUrls not like", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsIn(List<String> values) {
			addCriterion("WebUrls in", values, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsNotIn(List<String> values) {
			addCriterion("WebUrls not in", values, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsBetween(String value1, String value2) {
			addCriterion("WebUrls between", value1, value2, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsNotBetween(String value1, String value2) {
			addCriterion("WebUrls not between", value1, value2, "weburls");
			return (Criteria) this;
		}

		public Criteria andTraceabilitypathIsNull() {
			addCriterion("TraceabilityPath is null");
			return (Criteria) this;
		}

		public Criteria andTraceabilitypathIsNotNull() {
			addCriterion("TraceabilityPath is not null");
			return (Criteria) this;
		}

		public Criteria andTraceabilitypathEqualTo(Integer value) {
			addCriterion("TraceabilityPath =", value, "traceabilitypath");
			return (Criteria) this;
		}

		public Criteria andTraceabilitypathNotEqualTo(Integer value) {
			addCriterion("TraceabilityPath <>", value, "traceabilitypath");
			return (Criteria) this;
		}

		public Criteria andTraceabilitypathGreaterThan(Integer value) {
			addCriterion("TraceabilityPath >", value, "traceabilitypath");
			return (Criteria) this;
		}

		public Criteria andTraceabilitypathGreaterThanOrEqualTo(Integer value) {
			addCriterion("TraceabilityPath >=", value, "traceabilitypath");
			return (Criteria) this;
		}

		public Criteria andTraceabilitypathLessThan(Integer value) {
			addCriterion("TraceabilityPath <", value, "traceabilitypath");
			return (Criteria) this;
		}

		public Criteria andTraceabilitypathLessThanOrEqualTo(Integer value) {
			addCriterion("TraceabilityPath <=", value, "traceabilitypath");
			return (Criteria) this;
		}

		public Criteria andTraceabilitypathIn(List<Integer> values) {
			addCriterion("TraceabilityPath in", values, "traceabilitypath");
			return (Criteria) this;
		}

		public Criteria andTraceabilitypathNotIn(List<Integer> values) {
			addCriterion("TraceabilityPath not in", values, "traceabilitypath");
			return (Criteria) this;
		}

		public Criteria andTraceabilitypathBetween(Integer value1, Integer value2) {
			addCriterion("TraceabilityPath between", value1, value2, "traceabilitypath");
			return (Criteria) this;
		}

		public Criteria andTraceabilitypathNotBetween(Integer value1, Integer value2) {
			addCriterion("TraceabilityPath not between", value1, value2, "traceabilitypath");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkIsNull() {
			addCriterion("AdsIds_fk is null");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkIsNotNull() {
			addCriterion("AdsIds_fk is not null");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkEqualTo(String value) {
			addCriterion("AdsIds_fk =", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkNotEqualTo(String value) {
			addCriterion("AdsIds_fk <>", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkGreaterThan(String value) {
			addCriterion("AdsIds_fk >", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkGreaterThanOrEqualTo(String value) {
			addCriterion("AdsIds_fk >=", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkLessThan(String value) {
			addCriterion("AdsIds_fk <", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkLessThanOrEqualTo(String value) {
			addCriterion("AdsIds_fk <=", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkLike(String value) {
			addCriterion("AdsIds_fk like", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkNotLike(String value) {
			addCriterion("AdsIds_fk not like", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkIn(List<String> values) {
			addCriterion("AdsIds_fk in", values, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkNotIn(List<String> values) {
			addCriterion("AdsIds_fk not in", values, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkBetween(String value1, String value2) {
			addCriterion("AdsIds_fk between", value1, value2, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkNotBetween(String value1, String value2) {
			addCriterion("AdsIds_fk not between", value1, value2, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andFamilyproductFkIsNull() {
			addCriterion("Familyproduct_fk is null");
			return (Criteria) this;
		}

		public Criteria andFamilyproductFkIsNotNull() {
			addCriterion("Familyproduct_fk is not null");
			return (Criteria) this;
		}

		public Criteria andFamilyproductFkEqualTo(Long value) {
			addCriterion("Familyproduct_fk =", value, "familyproductFk");
			return (Criteria) this;
		}

		public Criteria andFamilyproductFkNotEqualTo(Long value) {
			addCriterion("Familyproduct_fk <>", value, "familyproductFk");
			return (Criteria) this;
		}

		public Criteria andFamilyproductFkGreaterThan(Long value) {
			addCriterion("Familyproduct_fk >", value, "familyproductFk");
			return (Criteria) this;
		}

		public Criteria andFamilyproductFkGreaterThanOrEqualTo(Long value) {
			addCriterion("Familyproduct_fk >=", value, "familyproductFk");
			return (Criteria) this;
		}

		public Criteria andFamilyproductFkLessThan(Long value) {
			addCriterion("Familyproduct_fk <", value, "familyproductFk");
			return (Criteria) this;
		}

		public Criteria andFamilyproductFkLessThanOrEqualTo(Long value) {
			addCriterion("Familyproduct_fk <=", value, "familyproductFk");
			return (Criteria) this;
		}

		public Criteria andFamilyproductFkIn(List<Long> values) {
			addCriterion("Familyproduct_fk in", values, "familyproductFk");
			return (Criteria) this;
		}

		public Criteria andFamilyproductFkNotIn(List<Long> values) {
			addCriterion("Familyproduct_fk not in", values, "familyproductFk");
			return (Criteria) this;
		}

		public Criteria andFamilyproductFkBetween(Long value1, Long value2) {
			addCriterion("Familyproduct_fk between", value1, value2, "familyproductFk");
			return (Criteria) this;
		}

		public Criteria andFamilyproductFkNotBetween(Long value1, Long value2) {
			addCriterion("Familyproduct_fk not between", value1, value2, "familyproductFk");
			return (Criteria) this;
		}

		public Criteria andContentobjIsNull() {
			addCriterion("ContentObj is null");
			return (Criteria) this;
		}

		public Criteria andContentobjIsNotNull() {
			addCriterion("ContentObj is not null");
			return (Criteria) this;
		}

		public Criteria andContentobjEqualTo(String value) {
			addCriterion("ContentObj =", value, "contentobj");
			return (Criteria) this;
		}

		public Criteria andContentobjNotEqualTo(String value) {
			addCriterion("ContentObj <>", value, "contentobj");
			return (Criteria) this;
		}

		public Criteria andContentobjGreaterThan(String value) {
			addCriterion("ContentObj >", value, "contentobj");
			return (Criteria) this;
		}

		public Criteria andContentobjGreaterThanOrEqualTo(String value) {
			addCriterion("ContentObj >=", value, "contentobj");
			return (Criteria) this;
		}

		public Criteria andContentobjLessThan(String value) {
			addCriterion("ContentObj <", value, "contentobj");
			return (Criteria) this;
		}

		public Criteria andContentobjLessThanOrEqualTo(String value) {
			addCriterion("ContentObj <=", value, "contentobj");
			return (Criteria) this;
		}

		public Criteria andContentobjLike(String value) {
			addCriterion("ContentObj like", value, "contentobj");
			return (Criteria) this;
		}

		public Criteria andContentobjNotLike(String value) {
			addCriterion("ContentObj not like", value, "contentobj");
			return (Criteria) this;
		}

		public Criteria andContentobjIn(List<String> values) {
			addCriterion("ContentObj in", values, "contentobj");
			return (Criteria) this;
		}

		public Criteria andContentobjNotIn(List<String> values) {
			addCriterion("ContentObj not in", values, "contentobj");
			return (Criteria) this;
		}

		public Criteria andContentobjBetween(String value1, String value2) {
			addCriterion("ContentObj between", value1, value2, "contentobj");
			return (Criteria) this;
		}

		public Criteria andContentobjNotBetween(String value1, String value2) {
			addCriterion("ContentObj not between", value1, value2, "contentobj");
			return (Criteria) this;
		}

		public Criteria andWorkhelpFkIsNull() {
			addCriterion("WorkHelp_fk is null");
			return (Criteria) this;
		}

		public Criteria andWorkhelpFkIsNotNull() {
			addCriterion("WorkHelp_fk is not null");
			return (Criteria) this;
		}

		public Criteria andWorkhelpFkEqualTo(String value) {
			addCriterion("WorkHelp_fk =", value, "workhelpFk");
			return (Criteria) this;
		}

		public Criteria andWorkhelpFkNotEqualTo(String value) {
			addCriterion("WorkHelp_fk <>", value, "workhelpFk");
			return (Criteria) this;
		}

		public Criteria andWorkhelpFkGreaterThan(String value) {
			addCriterion("WorkHelp_fk >", value, "workhelpFk");
			return (Criteria) this;
		}

		public Criteria andWorkhelpFkGreaterThanOrEqualTo(String value) {
			addCriterion("WorkHelp_fk >=", value, "workhelpFk");
			return (Criteria) this;
		}

		public Criteria andWorkhelpFkLessThan(String value) {
			addCriterion("WorkHelp_fk <", value, "workhelpFk");
			return (Criteria) this;
		}

		public Criteria andWorkhelpFkLessThanOrEqualTo(String value) {
			addCriterion("WorkHelp_fk <=", value, "workhelpFk");
			return (Criteria) this;
		}

		public Criteria andWorkhelpFkLike(String value) {
			addCriterion("WorkHelp_fk like", value, "workhelpFk");
			return (Criteria) this;
		}

		public Criteria andWorkhelpFkNotLike(String value) {
			addCriterion("WorkHelp_fk not like", value, "workhelpFk");
			return (Criteria) this;
		}

		public Criteria andWorkhelpFkIn(List<String> values) {
			addCriterion("WorkHelp_fk in", values, "workhelpFk");
			return (Criteria) this;
		}

		public Criteria andWorkhelpFkNotIn(List<String> values) {
			addCriterion("WorkHelp_fk not in", values, "workhelpFk");
			return (Criteria) this;
		}

		public Criteria andWorkhelpFkBetween(String value1, String value2) {
			addCriterion("WorkHelp_fk between", value1, value2, "workhelpFk");
			return (Criteria) this;
		}

		public Criteria andWorkhelpFkNotBetween(String value1, String value2) {
			addCriterion("WorkHelp_fk not between", value1, value2, "workhelpFk");
			return (Criteria) this;
		}

		public Criteria andShowlevelIsNull() {
			addCriterion("ShowLevel is null");
			return (Criteria) this;
		}

		public Criteria andShowlevelIsNotNull() {
			addCriterion("ShowLevel is not null");
			return (Criteria) this;
		}

		public Criteria andShowlevelEqualTo(Integer value) {
			addCriterion("ShowLevel =", value, "showlevel");
			return (Criteria) this;
		}

		public Criteria andShowlevelNotEqualTo(Integer value) {
			addCriterion("ShowLevel <>", value, "showlevel");
			return (Criteria) this;
		}

		public Criteria andShowlevelGreaterThan(Integer value) {
			addCriterion("ShowLevel >", value, "showlevel");
			return (Criteria) this;
		}

		public Criteria andShowlevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("ShowLevel >=", value, "showlevel");
			return (Criteria) this;
		}

		public Criteria andShowlevelLessThan(Integer value) {
			addCriterion("ShowLevel <", value, "showlevel");
			return (Criteria) this;
		}

		public Criteria andShowlevelLessThanOrEqualTo(Integer value) {
			addCriterion("ShowLevel <=", value, "showlevel");
			return (Criteria) this;
		}

		public Criteria andShowlevelIn(List<Integer> values) {
			addCriterion("ShowLevel in", values, "showlevel");
			return (Criteria) this;
		}

		public Criteria andShowlevelNotIn(List<Integer> values) {
			addCriterion("ShowLevel not in", values, "showlevel");
			return (Criteria) this;
		}

		public Criteria andShowlevelBetween(Integer value1, Integer value2) {
			addCriterion("ShowLevel between", value1, value2, "showlevel");
			return (Criteria) this;
		}

		public Criteria andShowlevelNotBetween(Integer value1, Integer value2) {
			addCriterion("ShowLevel not between", value1, value2, "showlevel");
			return (Criteria) this;
		}

		public Criteria andIsshowIsNull() {
			addCriterion("IsShow is null");
			return (Criteria) this;
		}

		public Criteria andIsshowIsNotNull() {
			addCriterion("IsShow is not null");
			return (Criteria) this;
		}

		public Criteria andIsshowEqualTo(Integer value) {
			addCriterion("IsShow =", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowNotEqualTo(Integer value) {
			addCriterion("IsShow <>", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowGreaterThan(Integer value) {
			addCriterion("IsShow >", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowGreaterThanOrEqualTo(Integer value) {
			addCriterion("IsShow >=", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowLessThan(Integer value) {
			addCriterion("IsShow <", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowLessThanOrEqualTo(Integer value) {
			addCriterion("IsShow <=", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowIn(List<Integer> values) {
			addCriterion("IsShow in", values, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowNotIn(List<Integer> values) {
			addCriterion("IsShow not in", values, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowBetween(Integer value1, Integer value2) {
			addCriterion("IsShow between", value1, value2, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowNotBetween(Integer value1, Integer value2) {
			addCriterion("IsShow not between", value1, value2, "isshow");
			return (Criteria) this;
		}

		public Criteria andCreatebyIsNull() {
			addCriterion("CreateBy is null");
			return (Criteria) this;
		}

		public Criteria andCreatebyIsNotNull() {
			addCriterion("CreateBy is not null");
			return (Criteria) this;
		}

		public Criteria andCreatebyEqualTo(Long value) {
			addCriterion("CreateBy =", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyNotEqualTo(Long value) {
			addCriterion("CreateBy <>", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyGreaterThan(Long value) {
			addCriterion("CreateBy >", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyGreaterThanOrEqualTo(Long value) {
			addCriterion("CreateBy >=", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyLessThan(Long value) {
			addCriterion("CreateBy <", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyLessThanOrEqualTo(Long value) {
			addCriterion("CreateBy <=", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyIn(List<Long> values) {
			addCriterion("CreateBy in", values, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyNotIn(List<Long> values) {
			addCriterion("CreateBy not in", values, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyBetween(Long value1, Long value2) {
			addCriterion("CreateBy between", value1, value2, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyNotBetween(Long value1, Long value2) {
			addCriterion("CreateBy not between", value1, value2, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNull() {
			addCriterion("CreateTime is null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNotNull() {
			addCriterion("CreateTime is not null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeEqualTo(Date value) {
			addCriterion("CreateTime =", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotEqualTo(Date value) {
			addCriterion("CreateTime <>", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThan(Date value) {
			addCriterion("CreateTime >", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CreateTime >=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThan(Date value) {
			addCriterion("CreateTime <", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
			addCriterion("CreateTime <=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIn(List<Date> values) {
			addCriterion("CreateTime in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotIn(List<Date> values) {
			addCriterion("CreateTime not in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeBetween(Date value1, Date value2) {
			addCriterion("CreateTime between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
			addCriterion("CreateTime not between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andDelflagIsNull() {
			addCriterion("DelFlag is null");
			return (Criteria) this;
		}

		public Criteria andDelflagIsNotNull() {
			addCriterion("DelFlag is not null");
			return (Criteria) this;
		}

		public Criteria andDelflagEqualTo(Integer value) {
			addCriterion("DelFlag =", value, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagNotEqualTo(Integer value) {
			addCriterion("DelFlag <>", value, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagGreaterThan(Integer value) {
			addCriterion("DelFlag >", value, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagGreaterThanOrEqualTo(Integer value) {
			addCriterion("DelFlag >=", value, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagLessThan(Integer value) {
			addCriterion("DelFlag <", value, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagLessThanOrEqualTo(Integer value) {
			addCriterion("DelFlag <=", value, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagIn(List<Integer> values) {
			addCriterion("DelFlag in", values, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagNotIn(List<Integer> values) {
			addCriterion("DelFlag not in", values, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagBetween(Integer value1, Integer value2) {
			addCriterion("DelFlag between", value1, value2, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagNotBetween(Integer value1, Integer value2) {
			addCriterion("DelFlag not between", value1, value2, "delflag");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table familytraceability
     *
     * @mbggenerated do_not_delete_during_merge Fri Feb 17 09:21:29 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}