package com.gafker.manage.entity;

import java.util.Date;

public class Familyfutureorders {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyfutureorders.id
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyfutureorders.UstringId
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String ustringid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyfutureorders.NameEn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String nameen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyfutureorders.NameCn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String namecn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyfutureorders.FamilyProduct_fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Long familyproductFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyfutureorders.OrderType
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer ordertype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyfutureorders.QrCode
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String qrcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyfutureorders.Idx
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyfutureorders.WebUrls
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String weburls;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyfutureorders.AdsIds__fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String adsidsFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyfutureorders.OrdersDesc
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String ordersdesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyfutureorders.OrderObj
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String orderobj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyfutureorders.OrderStatus
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer orderstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyfutureorders.DelFlag
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer delflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyfutureorders.UpdateBy
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Long updateby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyfutureorders.CreateBy
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Long createby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyfutureorders.CreateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyfutureorders.UpdateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Date updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyfutureorders.id
	 * @return  the value of familyfutureorders.id
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyfutureorders.id
	 * @param id  the value for familyfutureorders.id
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyfutureorders.UstringId
	 * @return  the value of familyfutureorders.UstringId
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getUstringid() {
		return ustringid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyfutureorders.UstringId
	 * @param ustringid  the value for familyfutureorders.UstringId
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setUstringid(String ustringid) {
		this.ustringid = ustringid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyfutureorders.NameEn
	 * @return  the value of familyfutureorders.NameEn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getNameen() {
		return nameen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyfutureorders.NameEn
	 * @param nameen  the value for familyfutureorders.NameEn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setNameen(String nameen) {
		this.nameen = nameen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyfutureorders.NameCn
	 * @return  the value of familyfutureorders.NameCn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getNamecn() {
		return namecn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyfutureorders.NameCn
	 * @param namecn  the value for familyfutureorders.NameCn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setNamecn(String namecn) {
		this.namecn = namecn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyfutureorders.FamilyProduct_fk
	 * @return  the value of familyfutureorders.FamilyProduct_fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Long getFamilyproductFk() {
		return familyproductFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyfutureorders.FamilyProduct_fk
	 * @param familyproductFk  the value for familyfutureorders.FamilyProduct_fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setFamilyproductFk(Long familyproductFk) {
		this.familyproductFk = familyproductFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyfutureorders.OrderType
	 * @return  the value of familyfutureorders.OrderType
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getOrdertype() {
		return ordertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyfutureorders.OrderType
	 * @param ordertype  the value for familyfutureorders.OrderType
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setOrdertype(Integer ordertype) {
		this.ordertype = ordertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyfutureorders.QrCode
	 * @return  the value of familyfutureorders.QrCode
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getQrcode() {
		return qrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyfutureorders.QrCode
	 * @param qrcode  the value for familyfutureorders.QrCode
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setQrcode(String qrcode) {
		this.qrcode = qrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyfutureorders.Idx
	 * @return  the value of familyfutureorders.Idx
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyfutureorders.Idx
	 * @param idx  the value for familyfutureorders.Idx
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyfutureorders.WebUrls
	 * @return  the value of familyfutureorders.WebUrls
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getWeburls() {
		return weburls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyfutureorders.WebUrls
	 * @param weburls  the value for familyfutureorders.WebUrls
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setWeburls(String weburls) {
		this.weburls = weburls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyfutureorders.AdsIds__fk
	 * @return  the value of familyfutureorders.AdsIds__fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getAdsidsFk() {
		return adsidsFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyfutureorders.AdsIds__fk
	 * @param adsidsFk  the value for familyfutureorders.AdsIds__fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setAdsidsFk(String adsidsFk) {
		this.adsidsFk = adsidsFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyfutureorders.OrdersDesc
	 * @return  the value of familyfutureorders.OrdersDesc
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getOrdersdesc() {
		return ordersdesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyfutureorders.OrdersDesc
	 * @param ordersdesc  the value for familyfutureorders.OrdersDesc
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setOrdersdesc(String ordersdesc) {
		this.ordersdesc = ordersdesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyfutureorders.OrderObj
	 * @return  the value of familyfutureorders.OrderObj
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getOrderobj() {
		return orderobj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyfutureorders.OrderObj
	 * @param orderobj  the value for familyfutureorders.OrderObj
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setOrderobj(String orderobj) {
		this.orderobj = orderobj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyfutureorders.OrderStatus
	 * @return  the value of familyfutureorders.OrderStatus
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getOrderstatus() {
		return orderstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyfutureorders.OrderStatus
	 * @param orderstatus  the value for familyfutureorders.OrderStatus
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setOrderstatus(Integer orderstatus) {
		this.orderstatus = orderstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyfutureorders.DelFlag
	 * @return  the value of familyfutureorders.DelFlag
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getDelflag() {
		return delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyfutureorders.DelFlag
	 * @param delflag  the value for familyfutureorders.DelFlag
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setDelflag(Integer delflag) {
		this.delflag = delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyfutureorders.UpdateBy
	 * @return  the value of familyfutureorders.UpdateBy
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Long getUpdateby() {
		return updateby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyfutureorders.UpdateBy
	 * @param updateby  the value for familyfutureorders.UpdateBy
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setUpdateby(Long updateby) {
		this.updateby = updateby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyfutureorders.CreateBy
	 * @return  the value of familyfutureorders.CreateBy
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Long getCreateby() {
		return createby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyfutureorders.CreateBy
	 * @param createby  the value for familyfutureorders.CreateBy
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setCreateby(Long createby) {
		this.createby = createby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyfutureorders.CreateTime
	 * @return  the value of familyfutureorders.CreateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyfutureorders.CreateTime
	 * @param createtime  the value for familyfutureorders.CreateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyfutureorders.UpdateTime
	 * @return  the value of familyfutureorders.UpdateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyfutureorders.UpdateTime
	 * @param updatetime  the value for familyfutureorders.UpdateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}
}