package com.gafker.manage.entity;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;

public class Familytraceability implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -1540709269703896482L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familytraceability.id
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familytraceability.UstringId
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String ustringid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familytraceability.NameEn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String nameen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familytraceability.NameCn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String namecn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familytraceability.Title
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familytraceability.Step
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer step;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familytraceability.Idx
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familytraceability.WebUrls
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String weburls;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familytraceability.TraceabilityPath
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer traceabilitypath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familytraceability.AdsIds_fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String adsidsFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familytraceability.Familyproduct_fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	@NotNull(message="产品Id必须有！")
	private Long familyproductFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familytraceability.ContentObj
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String contentobj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familytraceability.WorkHelp_fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String workhelpFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familytraceability.ShowLevel
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer showlevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familytraceability.IsShow
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer isshow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familytraceability.CreateBy
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Long createby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familytraceability.CreateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familytraceability.DelFlag
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer delflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familytraceability.id
	 * @return  the value of familytraceability.id
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familytraceability.id
	 * @param id  the value for familytraceability.id
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familytraceability.UstringId
	 * @return  the value of familytraceability.UstringId
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getUstringid() {
		return ustringid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familytraceability.UstringId
	 * @param ustringid  the value for familytraceability.UstringId
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setUstringid(String ustringid) {
		this.ustringid = ustringid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familytraceability.NameEn
	 * @return  the value of familytraceability.NameEn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getNameen() {
		return nameen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familytraceability.NameEn
	 * @param nameen  the value for familytraceability.NameEn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setNameen(String nameen) {
		this.nameen = nameen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familytraceability.NameCn
	 * @return  the value of familytraceability.NameCn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getNamecn() {
		return namecn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familytraceability.NameCn
	 * @param namecn  the value for familytraceability.NameCn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setNamecn(String namecn) {
		this.namecn = namecn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familytraceability.Title
	 * @return  the value of familytraceability.Title
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familytraceability.Title
	 * @param title  the value for familytraceability.Title
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familytraceability.Step
	 * @return  the value of familytraceability.Step
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getStep() {
		return step;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familytraceability.Step
	 * @param step  the value for familytraceability.Step
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setStep(Integer step) {
		this.step = step;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familytraceability.Idx
	 * @return  the value of familytraceability.Idx
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familytraceability.Idx
	 * @param idx  the value for familytraceability.Idx
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familytraceability.WebUrls
	 * @return  the value of familytraceability.WebUrls
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getWeburls() {
		return weburls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familytraceability.WebUrls
	 * @param weburls  the value for familytraceability.WebUrls
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setWeburls(String weburls) {
		this.weburls = weburls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familytraceability.TraceabilityPath
	 * @return  the value of familytraceability.TraceabilityPath
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getTraceabilitypath() {
		return traceabilitypath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familytraceability.TraceabilityPath
	 * @param traceabilitypath  the value for familytraceability.TraceabilityPath
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setTraceabilitypath(Integer traceabilitypath) {
		this.traceabilitypath = traceabilitypath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familytraceability.AdsIds_fk
	 * @return  the value of familytraceability.AdsIds_fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getAdsidsFk() {
		return adsidsFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familytraceability.AdsIds_fk
	 * @param adsidsFk  the value for familytraceability.AdsIds_fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setAdsidsFk(String adsidsFk) {
		this.adsidsFk = adsidsFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familytraceability.Familyproduct_fk
	 * @return  the value of familytraceability.Familyproduct_fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Long getFamilyproductFk() {
		return familyproductFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familytraceability.Familyproduct_fk
	 * @param familyproductFk  the value for familytraceability.Familyproduct_fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setFamilyproductFk(Long familyproductFk) {
		this.familyproductFk = familyproductFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familytraceability.ContentObj
	 * @return  the value of familytraceability.ContentObj
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getContentobj() {
		return contentobj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familytraceability.ContentObj
	 * @param contentobj  the value for familytraceability.ContentObj
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setContentobj(String contentobj) {
		this.contentobj = contentobj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familytraceability.WorkHelp_fk
	 * @return  the value of familytraceability.WorkHelp_fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getWorkhelpFk() {
		return workhelpFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familytraceability.WorkHelp_fk
	 * @param workhelpFk  the value for familytraceability.WorkHelp_fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setWorkhelpFk(String workhelpFk) {
		this.workhelpFk = workhelpFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familytraceability.ShowLevel
	 * @return  the value of familytraceability.ShowLevel
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getShowlevel() {
		return showlevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familytraceability.ShowLevel
	 * @param showlevel  the value for familytraceability.ShowLevel
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setShowlevel(Integer showlevel) {
		this.showlevel = showlevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familytraceability.IsShow
	 * @return  the value of familytraceability.IsShow
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getIsshow() {
		return isshow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familytraceability.IsShow
	 * @param isshow  the value for familytraceability.IsShow
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setIsshow(Integer isshow) {
		this.isshow = isshow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familytraceability.CreateBy
	 * @return  the value of familytraceability.CreateBy
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Long getCreateby() {
		return createby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familytraceability.CreateBy
	 * @param createby  the value for familytraceability.CreateBy
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setCreateby(Long createby) {
		this.createby = createby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familytraceability.CreateTime
	 * @return  the value of familytraceability.CreateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familytraceability.CreateTime
	 * @param createtime  the value for familytraceability.CreateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familytraceability.DelFlag
	 * @return  the value of familytraceability.DelFlag
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getDelflag() {
		return delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familytraceability.DelFlag
	 * @param delflag  the value for familytraceability.DelFlag
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setDelflag(Integer delflag) {
		this.delflag = delflag;
	}
}