package com.gafker.manage.entity;

import java.util.Date;

public class Familyclothesinventory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.id
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.NameEn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String nameen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.NameCn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String namecn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.Idx
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.Expired
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Date expired;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.ExpiredIs
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer expiredis;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.SizeObject
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String sizeobject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.ImagesList
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String imageslist;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.ImagesDefault
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String imagesdefault;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.WebUrls
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String weburls;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.AdsIds__fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String adsidsFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.Qrcode
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String qrcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.FamilyClothespress_fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Long familyclothespressFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.ClothesType
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer clothestype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.SubClothesType
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer subclothestype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.Season
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String season;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.BuyObject
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String buyobject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.BuyTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Date buytime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.CreateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyclothesinventory.UpdateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Date updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.id
	 * @return  the value of familyclothesinventory.id
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.id
	 * @param id  the value for familyclothesinventory.id
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.NameEn
	 * @return  the value of familyclothesinventory.NameEn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getNameen() {
		return nameen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.NameEn
	 * @param nameen  the value for familyclothesinventory.NameEn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setNameen(String nameen) {
		this.nameen = nameen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.NameCn
	 * @return  the value of familyclothesinventory.NameCn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getNamecn() {
		return namecn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.NameCn
	 * @param namecn  the value for familyclothesinventory.NameCn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setNamecn(String namecn) {
		this.namecn = namecn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.Idx
	 * @return  the value of familyclothesinventory.Idx
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.Idx
	 * @param idx  the value for familyclothesinventory.Idx
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.Expired
	 * @return  the value of familyclothesinventory.Expired
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Date getExpired() {
		return expired;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.Expired
	 * @param expired  the value for familyclothesinventory.Expired
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setExpired(Date expired) {
		this.expired = expired;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.ExpiredIs
	 * @return  the value of familyclothesinventory.ExpiredIs
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getExpiredis() {
		return expiredis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.ExpiredIs
	 * @param expiredis  the value for familyclothesinventory.ExpiredIs
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setExpiredis(Integer expiredis) {
		this.expiredis = expiredis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.SizeObject
	 * @return  the value of familyclothesinventory.SizeObject
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getSizeobject() {
		return sizeobject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.SizeObject
	 * @param sizeobject  the value for familyclothesinventory.SizeObject
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setSizeobject(String sizeobject) {
		this.sizeobject = sizeobject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.ImagesList
	 * @return  the value of familyclothesinventory.ImagesList
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getImageslist() {
		return imageslist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.ImagesList
	 * @param imageslist  the value for familyclothesinventory.ImagesList
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setImageslist(String imageslist) {
		this.imageslist = imageslist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.ImagesDefault
	 * @return  the value of familyclothesinventory.ImagesDefault
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getImagesdefault() {
		return imagesdefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.ImagesDefault
	 * @param imagesdefault  the value for familyclothesinventory.ImagesDefault
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setImagesdefault(String imagesdefault) {
		this.imagesdefault = imagesdefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.WebUrls
	 * @return  the value of familyclothesinventory.WebUrls
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getWeburls() {
		return weburls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.WebUrls
	 * @param weburls  the value for familyclothesinventory.WebUrls
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setWeburls(String weburls) {
		this.weburls = weburls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.AdsIds__fk
	 * @return  the value of familyclothesinventory.AdsIds__fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getAdsidsFk() {
		return adsidsFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.AdsIds__fk
	 * @param adsidsFk  the value for familyclothesinventory.AdsIds__fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setAdsidsFk(String adsidsFk) {
		this.adsidsFk = adsidsFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.Qrcode
	 * @return  the value of familyclothesinventory.Qrcode
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getQrcode() {
		return qrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.Qrcode
	 * @param qrcode  the value for familyclothesinventory.Qrcode
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setQrcode(String qrcode) {
		this.qrcode = qrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.FamilyClothespress_fk
	 * @return  the value of familyclothesinventory.FamilyClothespress_fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Long getFamilyclothespressFk() {
		return familyclothespressFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.FamilyClothespress_fk
	 * @param familyclothespressFk  the value for familyclothesinventory.FamilyClothespress_fk
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setFamilyclothespressFk(Long familyclothespressFk) {
		this.familyclothespressFk = familyclothespressFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.ClothesType
	 * @return  the value of familyclothesinventory.ClothesType
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getClothestype() {
		return clothestype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.ClothesType
	 * @param clothestype  the value for familyclothesinventory.ClothesType
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setClothestype(Integer clothestype) {
		this.clothestype = clothestype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.SubClothesType
	 * @return  the value of familyclothesinventory.SubClothesType
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getSubclothestype() {
		return subclothestype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.SubClothesType
	 * @param subclothestype  the value for familyclothesinventory.SubClothesType
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setSubclothestype(Integer subclothestype) {
		this.subclothestype = subclothestype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.Season
	 * @return  the value of familyclothesinventory.Season
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getSeason() {
		return season;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.Season
	 * @param season  the value for familyclothesinventory.Season
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setSeason(String season) {
		this.season = season;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.BuyObject
	 * @return  the value of familyclothesinventory.BuyObject
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getBuyobject() {
		return buyobject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.BuyObject
	 * @param buyobject  the value for familyclothesinventory.BuyObject
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setBuyobject(String buyobject) {
		this.buyobject = buyobject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.BuyTime
	 * @return  the value of familyclothesinventory.BuyTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Date getBuytime() {
		return buytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.BuyTime
	 * @param buytime  the value for familyclothesinventory.BuyTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setBuytime(Date buytime) {
		this.buytime = buytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.CreateTime
	 * @return  the value of familyclothesinventory.CreateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.CreateTime
	 * @param createtime  the value for familyclothesinventory.CreateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyclothesinventory.UpdateTime
	 * @return  the value of familyclothesinventory.UpdateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyclothesinventory.UpdateTime
	 * @param updatetime  the value for familyclothesinventory.UpdateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}
}