package com.gafker.manage.entity;

import java.util.Date;

public class Pagetest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pagetest.id
     *
     * @mbggenerated Thu Jun 15 23:40:22 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pagetest.qrcode
     *
     * @mbggenerated Thu Jun 15 23:40:22 CST 2017
     */
    private String qrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pagetest.start_time
     *
     * @mbggenerated Thu Jun 15 23:40:22 CST 2017
     */
    private Date startTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pagetest.id
     *
     * @return the value of pagetest.id
     *
     * @mbggenerated Thu Jun 15 23:40:22 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pagetest.id
     *
     * @param id the value for pagetest.id
     *
     * @mbggenerated Thu Jun 15 23:40:22 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pagetest.qrcode
     *
     * @return the value of pagetest.qrcode
     *
     * @mbggenerated Thu Jun 15 23:40:22 CST 2017
     */
    public String getQrcode() {
        return qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pagetest.qrcode
     *
     * @param qrcode the value for pagetest.qrcode
     *
     * @mbggenerated Thu Jun 15 23:40:22 CST 2017
     */
    public void setQrcode(String qrcode) {
        this.qrcode = qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pagetest.start_time
     *
     * @return the value of pagetest.start_time
     *
     * @mbggenerated Thu Jun 15 23:40:22 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pagetest.start_time
     *
     * @param startTime the value for pagetest.start_time
     *
     * @mbggenerated Thu Jun 15 23:40:22 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
}