package com.gafker.manage.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserbodysizeExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table userbodysize
	 * @mbg.generated  Thu Apr 13 21:33:56 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table userbodysize
	 * @mbg.generated  Thu Apr 13 21:33:56 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table userbodysize
	 * @mbg.generated  Thu Apr 13 21:33:56 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userbodysize
	 * @mbg.generated  Thu Apr 13 21:33:56 CST 2017
	 */
	public UserbodysizeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userbodysize
	 * @mbg.generated  Thu Apr 13 21:33:56 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userbodysize
	 * @mbg.generated  Thu Apr 13 21:33:56 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userbodysize
	 * @mbg.generated  Thu Apr 13 21:33:56 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userbodysize
	 * @mbg.generated  Thu Apr 13 21:33:56 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userbodysize
	 * @mbg.generated  Thu Apr 13 21:33:56 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userbodysize
	 * @mbg.generated  Thu Apr 13 21:33:56 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userbodysize
	 * @mbg.generated  Thu Apr 13 21:33:56 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userbodysize
	 * @mbg.generated  Thu Apr 13 21:33:56 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userbodysize
	 * @mbg.generated  Thu Apr 13 21:33:56 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userbodysize
	 * @mbg.generated  Thu Apr 13 21:33:56 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table userbodysize
	 * @mbg.generated  Thu Apr 13 21:33:56 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameenIsNull() {
			addCriterion("NameEn is null");
			return (Criteria) this;
		}

		public Criteria andNameenIsNotNull() {
			addCriterion("NameEn is not null");
			return (Criteria) this;
		}

		public Criteria andNameenEqualTo(String value) {
			addCriterion("NameEn =", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenNotEqualTo(String value) {
			addCriterion("NameEn <>", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenGreaterThan(String value) {
			addCriterion("NameEn >", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenGreaterThanOrEqualTo(String value) {
			addCriterion("NameEn >=", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenLessThan(String value) {
			addCriterion("NameEn <", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenLessThanOrEqualTo(String value) {
			addCriterion("NameEn <=", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenLike(String value) {
			addCriterion("NameEn like", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenNotLike(String value) {
			addCriterion("NameEn not like", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenIn(List<String> values) {
			addCriterion("NameEn in", values, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenNotIn(List<String> values) {
			addCriterion("NameEn not in", values, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenBetween(String value1, String value2) {
			addCriterion("NameEn between", value1, value2, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenNotBetween(String value1, String value2) {
			addCriterion("NameEn not between", value1, value2, "nameen");
			return (Criteria) this;
		}

		public Criteria andNamecnIsNull() {
			addCriterion("NameCn is null");
			return (Criteria) this;
		}

		public Criteria andNamecnIsNotNull() {
			addCriterion("NameCn is not null");
			return (Criteria) this;
		}

		public Criteria andNamecnEqualTo(String value) {
			addCriterion("NameCn =", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnNotEqualTo(String value) {
			addCriterion("NameCn <>", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnGreaterThan(String value) {
			addCriterion("NameCn >", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnGreaterThanOrEqualTo(String value) {
			addCriterion("NameCn >=", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnLessThan(String value) {
			addCriterion("NameCn <", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnLessThanOrEqualTo(String value) {
			addCriterion("NameCn <=", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnLike(String value) {
			addCriterion("NameCn like", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnNotLike(String value) {
			addCriterion("NameCn not like", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnIn(List<String> values) {
			addCriterion("NameCn in", values, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnNotIn(List<String> values) {
			addCriterion("NameCn not in", values, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnBetween(String value1, String value2) {
			addCriterion("NameCn between", value1, value2, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnNotBetween(String value1, String value2) {
			addCriterion("NameCn not between", value1, value2, "namecn");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("UserId is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("UserId is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(Long value) {
			addCriterion("UserId =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(Long value) {
			addCriterion("UserId <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(Long value) {
			addCriterion("UserId >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(Long value) {
			addCriterion("UserId >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(Long value) {
			addCriterion("UserId <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(Long value) {
			addCriterion("UserId <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<Long> values) {
			addCriterion("UserId in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<Long> values) {
			addCriterion("UserId not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(Long value1, Long value2) {
			addCriterion("UserId between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(Long value1, Long value2) {
			addCriterion("UserId not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andBodyheightIsNull() {
			addCriterion("BodyHeight is null");
			return (Criteria) this;
		}

		public Criteria andBodyheightIsNotNull() {
			addCriterion("BodyHeight is not null");
			return (Criteria) this;
		}

		public Criteria andBodyheightEqualTo(Double value) {
			addCriterion("BodyHeight =", value, "bodyheight");
			return (Criteria) this;
		}

		public Criteria andBodyheightNotEqualTo(Double value) {
			addCriterion("BodyHeight <>", value, "bodyheight");
			return (Criteria) this;
		}

		public Criteria andBodyheightGreaterThan(Double value) {
			addCriterion("BodyHeight >", value, "bodyheight");
			return (Criteria) this;
		}

		public Criteria andBodyheightGreaterThanOrEqualTo(Double value) {
			addCriterion("BodyHeight >=", value, "bodyheight");
			return (Criteria) this;
		}

		public Criteria andBodyheightLessThan(Double value) {
			addCriterion("BodyHeight <", value, "bodyheight");
			return (Criteria) this;
		}

		public Criteria andBodyheightLessThanOrEqualTo(Double value) {
			addCriterion("BodyHeight <=", value, "bodyheight");
			return (Criteria) this;
		}

		public Criteria andBodyheightIn(List<Double> values) {
			addCriterion("BodyHeight in", values, "bodyheight");
			return (Criteria) this;
		}

		public Criteria andBodyheightNotIn(List<Double> values) {
			addCriterion("BodyHeight not in", values, "bodyheight");
			return (Criteria) this;
		}

		public Criteria andBodyheightBetween(Double value1, Double value2) {
			addCriterion("BodyHeight between", value1, value2, "bodyheight");
			return (Criteria) this;
		}

		public Criteria andBodyheightNotBetween(Double value1, Double value2) {
			addCriterion("BodyHeight not between", value1, value2, "bodyheight");
			return (Criteria) this;
		}

		public Criteria andBodyweightIsNull() {
			addCriterion("BodyWeight is null");
			return (Criteria) this;
		}

		public Criteria andBodyweightIsNotNull() {
			addCriterion("BodyWeight is not null");
			return (Criteria) this;
		}

		public Criteria andBodyweightEqualTo(Double value) {
			addCriterion("BodyWeight =", value, "bodyweight");
			return (Criteria) this;
		}

		public Criteria andBodyweightNotEqualTo(Double value) {
			addCriterion("BodyWeight <>", value, "bodyweight");
			return (Criteria) this;
		}

		public Criteria andBodyweightGreaterThan(Double value) {
			addCriterion("BodyWeight >", value, "bodyweight");
			return (Criteria) this;
		}

		public Criteria andBodyweightGreaterThanOrEqualTo(Double value) {
			addCriterion("BodyWeight >=", value, "bodyweight");
			return (Criteria) this;
		}

		public Criteria andBodyweightLessThan(Double value) {
			addCriterion("BodyWeight <", value, "bodyweight");
			return (Criteria) this;
		}

		public Criteria andBodyweightLessThanOrEqualTo(Double value) {
			addCriterion("BodyWeight <=", value, "bodyweight");
			return (Criteria) this;
		}

		public Criteria andBodyweightIn(List<Double> values) {
			addCriterion("BodyWeight in", values, "bodyweight");
			return (Criteria) this;
		}

		public Criteria andBodyweightNotIn(List<Double> values) {
			addCriterion("BodyWeight not in", values, "bodyweight");
			return (Criteria) this;
		}

		public Criteria andBodyweightBetween(Double value1, Double value2) {
			addCriterion("BodyWeight between", value1, value2, "bodyweight");
			return (Criteria) this;
		}

		public Criteria andBodyweightNotBetween(Double value1, Double value2) {
			addCriterion("BodyWeight not between", value1, value2, "bodyweight");
			return (Criteria) this;
		}

		public Criteria andHatsizeIsNull() {
			addCriterion("HatSize is null");
			return (Criteria) this;
		}

		public Criteria andHatsizeIsNotNull() {
			addCriterion("HatSize is not null");
			return (Criteria) this;
		}

		public Criteria andHatsizeEqualTo(Double value) {
			addCriterion("HatSize =", value, "hatsize");
			return (Criteria) this;
		}

		public Criteria andHatsizeNotEqualTo(Double value) {
			addCriterion("HatSize <>", value, "hatsize");
			return (Criteria) this;
		}

		public Criteria andHatsizeGreaterThan(Double value) {
			addCriterion("HatSize >", value, "hatsize");
			return (Criteria) this;
		}

		public Criteria andHatsizeGreaterThanOrEqualTo(Double value) {
			addCriterion("HatSize >=", value, "hatsize");
			return (Criteria) this;
		}

		public Criteria andHatsizeLessThan(Double value) {
			addCriterion("HatSize <", value, "hatsize");
			return (Criteria) this;
		}

		public Criteria andHatsizeLessThanOrEqualTo(Double value) {
			addCriterion("HatSize <=", value, "hatsize");
			return (Criteria) this;
		}

		public Criteria andHatsizeIn(List<Double> values) {
			addCriterion("HatSize in", values, "hatsize");
			return (Criteria) this;
		}

		public Criteria andHatsizeNotIn(List<Double> values) {
			addCriterion("HatSize not in", values, "hatsize");
			return (Criteria) this;
		}

		public Criteria andHatsizeBetween(Double value1, Double value2) {
			addCriterion("HatSize between", value1, value2, "hatsize");
			return (Criteria) this;
		}

		public Criteria andHatsizeNotBetween(Double value1, Double value2) {
			addCriterion("HatSize not between", value1, value2, "hatsize");
			return (Criteria) this;
		}

		public Criteria andCoatsizeobjIsNull() {
			addCriterion("CoatSizeObj is null");
			return (Criteria) this;
		}

		public Criteria andCoatsizeobjIsNotNull() {
			addCriterion("CoatSizeObj is not null");
			return (Criteria) this;
		}

		public Criteria andCoatsizeobjEqualTo(Double value) {
			addCriterion("CoatSizeObj =", value, "coatsizeobj");
			return (Criteria) this;
		}

		public Criteria andCoatsizeobjNotEqualTo(Double value) {
			addCriterion("CoatSizeObj <>", value, "coatsizeobj");
			return (Criteria) this;
		}

		public Criteria andCoatsizeobjGreaterThan(Double value) {
			addCriterion("CoatSizeObj >", value, "coatsizeobj");
			return (Criteria) this;
		}

		public Criteria andCoatsizeobjGreaterThanOrEqualTo(Double value) {
			addCriterion("CoatSizeObj >=", value, "coatsizeobj");
			return (Criteria) this;
		}

		public Criteria andCoatsizeobjLessThan(Double value) {
			addCriterion("CoatSizeObj <", value, "coatsizeobj");
			return (Criteria) this;
		}

		public Criteria andCoatsizeobjLessThanOrEqualTo(Double value) {
			addCriterion("CoatSizeObj <=", value, "coatsizeobj");
			return (Criteria) this;
		}

		public Criteria andCoatsizeobjIn(List<Double> values) {
			addCriterion("CoatSizeObj in", values, "coatsizeobj");
			return (Criteria) this;
		}

		public Criteria andCoatsizeobjNotIn(List<Double> values) {
			addCriterion("CoatSizeObj not in", values, "coatsizeobj");
			return (Criteria) this;
		}

		public Criteria andCoatsizeobjBetween(Double value1, Double value2) {
			addCriterion("CoatSizeObj between", value1, value2, "coatsizeobj");
			return (Criteria) this;
		}

		public Criteria andCoatsizeobjNotBetween(Double value1, Double value2) {
			addCriterion("CoatSizeObj not between", value1, value2, "coatsizeobj");
			return (Criteria) this;
		}

		public Criteria andHandhatsizeIsNull() {
			addCriterion("HandHatSize is null");
			return (Criteria) this;
		}

		public Criteria andHandhatsizeIsNotNull() {
			addCriterion("HandHatSize is not null");
			return (Criteria) this;
		}

		public Criteria andHandhatsizeEqualTo(Double value) {
			addCriterion("HandHatSize =", value, "handhatsize");
			return (Criteria) this;
		}

		public Criteria andHandhatsizeNotEqualTo(Double value) {
			addCriterion("HandHatSize <>", value, "handhatsize");
			return (Criteria) this;
		}

		public Criteria andHandhatsizeGreaterThan(Double value) {
			addCriterion("HandHatSize >", value, "handhatsize");
			return (Criteria) this;
		}

		public Criteria andHandhatsizeGreaterThanOrEqualTo(Double value) {
			addCriterion("HandHatSize >=", value, "handhatsize");
			return (Criteria) this;
		}

		public Criteria andHandhatsizeLessThan(Double value) {
			addCriterion("HandHatSize <", value, "handhatsize");
			return (Criteria) this;
		}

		public Criteria andHandhatsizeLessThanOrEqualTo(Double value) {
			addCriterion("HandHatSize <=", value, "handhatsize");
			return (Criteria) this;
		}

		public Criteria andHandhatsizeIn(List<Double> values) {
			addCriterion("HandHatSize in", values, "handhatsize");
			return (Criteria) this;
		}

		public Criteria andHandhatsizeNotIn(List<Double> values) {
			addCriterion("HandHatSize not in", values, "handhatsize");
			return (Criteria) this;
		}

		public Criteria andHandhatsizeBetween(Double value1, Double value2) {
			addCriterion("HandHatSize between", value1, value2, "handhatsize");
			return (Criteria) this;
		}

		public Criteria andHandhatsizeNotBetween(Double value1, Double value2) {
			addCriterion("HandHatSize not between", value1, value2, "handhatsize");
			return (Criteria) this;
		}

		public Criteria andWaistsizeIsNull() {
			addCriterion("WaistSize is null");
			return (Criteria) this;
		}

		public Criteria andWaistsizeIsNotNull() {
			addCriterion("WaistSize is not null");
			return (Criteria) this;
		}

		public Criteria andWaistsizeEqualTo(Double value) {
			addCriterion("WaistSize =", value, "waistsize");
			return (Criteria) this;
		}

		public Criteria andWaistsizeNotEqualTo(Double value) {
			addCriterion("WaistSize <>", value, "waistsize");
			return (Criteria) this;
		}

		public Criteria andWaistsizeGreaterThan(Double value) {
			addCriterion("WaistSize >", value, "waistsize");
			return (Criteria) this;
		}

		public Criteria andWaistsizeGreaterThanOrEqualTo(Double value) {
			addCriterion("WaistSize >=", value, "waistsize");
			return (Criteria) this;
		}

		public Criteria andWaistsizeLessThan(Double value) {
			addCriterion("WaistSize <", value, "waistsize");
			return (Criteria) this;
		}

		public Criteria andWaistsizeLessThanOrEqualTo(Double value) {
			addCriterion("WaistSize <=", value, "waistsize");
			return (Criteria) this;
		}

		public Criteria andWaistsizeIn(List<Double> values) {
			addCriterion("WaistSize in", values, "waistsize");
			return (Criteria) this;
		}

		public Criteria andWaistsizeNotIn(List<Double> values) {
			addCriterion("WaistSize not in", values, "waistsize");
			return (Criteria) this;
		}

		public Criteria andWaistsizeBetween(Double value1, Double value2) {
			addCriterion("WaistSize between", value1, value2, "waistsize");
			return (Criteria) this;
		}

		public Criteria andWaistsizeNotBetween(Double value1, Double value2) {
			addCriterion("WaistSize not between", value1, value2, "waistsize");
			return (Criteria) this;
		}

		public Criteria andTrouserssizeobjIsNull() {
			addCriterion("TrousersSizeObj is null");
			return (Criteria) this;
		}

		public Criteria andTrouserssizeobjIsNotNull() {
			addCriterion("TrousersSizeObj is not null");
			return (Criteria) this;
		}

		public Criteria andTrouserssizeobjEqualTo(Double value) {
			addCriterion("TrousersSizeObj =", value, "trouserssizeobj");
			return (Criteria) this;
		}

		public Criteria andTrouserssizeobjNotEqualTo(Double value) {
			addCriterion("TrousersSizeObj <>", value, "trouserssizeobj");
			return (Criteria) this;
		}

		public Criteria andTrouserssizeobjGreaterThan(Double value) {
			addCriterion("TrousersSizeObj >", value, "trouserssizeobj");
			return (Criteria) this;
		}

		public Criteria andTrouserssizeobjGreaterThanOrEqualTo(Double value) {
			addCriterion("TrousersSizeObj >=", value, "trouserssizeobj");
			return (Criteria) this;
		}

		public Criteria andTrouserssizeobjLessThan(Double value) {
			addCriterion("TrousersSizeObj <", value, "trouserssizeobj");
			return (Criteria) this;
		}

		public Criteria andTrouserssizeobjLessThanOrEqualTo(Double value) {
			addCriterion("TrousersSizeObj <=", value, "trouserssizeobj");
			return (Criteria) this;
		}

		public Criteria andTrouserssizeobjIn(List<Double> values) {
			addCriterion("TrousersSizeObj in", values, "trouserssizeobj");
			return (Criteria) this;
		}

		public Criteria andTrouserssizeobjNotIn(List<Double> values) {
			addCriterion("TrousersSizeObj not in", values, "trouserssizeobj");
			return (Criteria) this;
		}

		public Criteria andTrouserssizeobjBetween(Double value1, Double value2) {
			addCriterion("TrousersSizeObj between", value1, value2, "trouserssizeobj");
			return (Criteria) this;
		}

		public Criteria andTrouserssizeobjNotBetween(Double value1, Double value2) {
			addCriterion("TrousersSizeObj not between", value1, value2, "trouserssizeobj");
			return (Criteria) this;
		}

		public Criteria andShoessizeIsNull() {
			addCriterion("ShoesSize is null");
			return (Criteria) this;
		}

		public Criteria andShoessizeIsNotNull() {
			addCriterion("ShoesSize is not null");
			return (Criteria) this;
		}

		public Criteria andShoessizeEqualTo(Double value) {
			addCriterion("ShoesSize =", value, "shoessize");
			return (Criteria) this;
		}

		public Criteria andShoessizeNotEqualTo(Double value) {
			addCriterion("ShoesSize <>", value, "shoessize");
			return (Criteria) this;
		}

		public Criteria andShoessizeGreaterThan(Double value) {
			addCriterion("ShoesSize >", value, "shoessize");
			return (Criteria) this;
		}

		public Criteria andShoessizeGreaterThanOrEqualTo(Double value) {
			addCriterion("ShoesSize >=", value, "shoessize");
			return (Criteria) this;
		}

		public Criteria andShoessizeLessThan(Double value) {
			addCriterion("ShoesSize <", value, "shoessize");
			return (Criteria) this;
		}

		public Criteria andShoessizeLessThanOrEqualTo(Double value) {
			addCriterion("ShoesSize <=", value, "shoessize");
			return (Criteria) this;
		}

		public Criteria andShoessizeIn(List<Double> values) {
			addCriterion("ShoesSize in", values, "shoessize");
			return (Criteria) this;
		}

		public Criteria andShoessizeNotIn(List<Double> values) {
			addCriterion("ShoesSize not in", values, "shoessize");
			return (Criteria) this;
		}

		public Criteria andShoessizeBetween(Double value1, Double value2) {
			addCriterion("ShoesSize between", value1, value2, "shoessize");
			return (Criteria) this;
		}

		public Criteria andShoessizeNotBetween(Double value1, Double value2) {
			addCriterion("ShoesSize not between", value1, value2, "shoessize");
			return (Criteria) this;
		}

		public Criteria andBodytypeIsNull() {
			addCriterion("BodyType is null");
			return (Criteria) this;
		}

		public Criteria andBodytypeIsNotNull() {
			addCriterion("BodyType is not null");
			return (Criteria) this;
		}

		public Criteria andBodytypeEqualTo(String value) {
			addCriterion("BodyType =", value, "bodytype");
			return (Criteria) this;
		}

		public Criteria andBodytypeNotEqualTo(String value) {
			addCriterion("BodyType <>", value, "bodytype");
			return (Criteria) this;
		}

		public Criteria andBodytypeGreaterThan(String value) {
			addCriterion("BodyType >", value, "bodytype");
			return (Criteria) this;
		}

		public Criteria andBodytypeGreaterThanOrEqualTo(String value) {
			addCriterion("BodyType >=", value, "bodytype");
			return (Criteria) this;
		}

		public Criteria andBodytypeLessThan(String value) {
			addCriterion("BodyType <", value, "bodytype");
			return (Criteria) this;
		}

		public Criteria andBodytypeLessThanOrEqualTo(String value) {
			addCriterion("BodyType <=", value, "bodytype");
			return (Criteria) this;
		}

		public Criteria andBodytypeLike(String value) {
			addCriterion("BodyType like", value, "bodytype");
			return (Criteria) this;
		}

		public Criteria andBodytypeNotLike(String value) {
			addCriterion("BodyType not like", value, "bodytype");
			return (Criteria) this;
		}

		public Criteria andBodytypeIn(List<String> values) {
			addCriterion("BodyType in", values, "bodytype");
			return (Criteria) this;
		}

		public Criteria andBodytypeNotIn(List<String> values) {
			addCriterion("BodyType not in", values, "bodytype");
			return (Criteria) this;
		}

		public Criteria andBodytypeBetween(String value1, String value2) {
			addCriterion("BodyType between", value1, value2, "bodytype");
			return (Criteria) this;
		}

		public Criteria andBodytypeNotBetween(String value1, String value2) {
			addCriterion("BodyType not between", value1, value2, "bodytype");
			return (Criteria) this;
		}

		public Criteria andIdxIsNull() {
			addCriterion("Idx is null");
			return (Criteria) this;
		}

		public Criteria andIdxIsNotNull() {
			addCriterion("Idx is not null");
			return (Criteria) this;
		}

		public Criteria andIdxEqualTo(Integer value) {
			addCriterion("Idx =", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxNotEqualTo(Integer value) {
			addCriterion("Idx <>", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxGreaterThan(Integer value) {
			addCriterion("Idx >", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxGreaterThanOrEqualTo(Integer value) {
			addCriterion("Idx >=", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxLessThan(Integer value) {
			addCriterion("Idx <", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxLessThanOrEqualTo(Integer value) {
			addCriterion("Idx <=", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxIn(List<Integer> values) {
			addCriterion("Idx in", values, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxNotIn(List<Integer> values) {
			addCriterion("Idx not in", values, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxBetween(Integer value1, Integer value2) {
			addCriterion("Idx between", value1, value2, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxNotBetween(Integer value1, Integer value2) {
			addCriterion("Idx not between", value1, value2, "idx");
			return (Criteria) this;
		}

		public Criteria andWeburlsIsNull() {
			addCriterion("WebUrls is null");
			return (Criteria) this;
		}

		public Criteria andWeburlsIsNotNull() {
			addCriterion("WebUrls is not null");
			return (Criteria) this;
		}

		public Criteria andWeburlsEqualTo(String value) {
			addCriterion("WebUrls =", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsNotEqualTo(String value) {
			addCriterion("WebUrls <>", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsGreaterThan(String value) {
			addCriterion("WebUrls >", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsGreaterThanOrEqualTo(String value) {
			addCriterion("WebUrls >=", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsLessThan(String value) {
			addCriterion("WebUrls <", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsLessThanOrEqualTo(String value) {
			addCriterion("WebUrls <=", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsLike(String value) {
			addCriterion("WebUrls like", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsNotLike(String value) {
			addCriterion("WebUrls not like", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsIn(List<String> values) {
			addCriterion("WebUrls in", values, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsNotIn(List<String> values) {
			addCriterion("WebUrls not in", values, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsBetween(String value1, String value2) {
			addCriterion("WebUrls between", value1, value2, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsNotBetween(String value1, String value2) {
			addCriterion("WebUrls not between", value1, value2, "weburls");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkIsNull() {
			addCriterion("AdsIds_fk is null");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkIsNotNull() {
			addCriterion("AdsIds_fk is not null");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkEqualTo(String value) {
			addCriterion("AdsIds_fk =", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkNotEqualTo(String value) {
			addCriterion("AdsIds_fk <>", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkGreaterThan(String value) {
			addCriterion("AdsIds_fk >", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkGreaterThanOrEqualTo(String value) {
			addCriterion("AdsIds_fk >=", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkLessThan(String value) {
			addCriterion("AdsIds_fk <", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkLessThanOrEqualTo(String value) {
			addCriterion("AdsIds_fk <=", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkLike(String value) {
			addCriterion("AdsIds_fk like", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkNotLike(String value) {
			addCriterion("AdsIds_fk not like", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkIn(List<String> values) {
			addCriterion("AdsIds_fk in", values, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkNotIn(List<String> values) {
			addCriterion("AdsIds_fk not in", values, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkBetween(String value1, String value2) {
			addCriterion("AdsIds_fk between", value1, value2, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkNotBetween(String value1, String value2) {
			addCriterion("AdsIds_fk not between", value1, value2, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andDelflagIsNull() {
			addCriterion("DelFlag is null");
			return (Criteria) this;
		}

		public Criteria andDelflagIsNotNull() {
			addCriterion("DelFlag is not null");
			return (Criteria) this;
		}

		public Criteria andDelflagEqualTo(Integer value) {
			addCriterion("DelFlag =", value, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagNotEqualTo(Integer value) {
			addCriterion("DelFlag <>", value, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagGreaterThan(Integer value) {
			addCriterion("DelFlag >", value, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagGreaterThanOrEqualTo(Integer value) {
			addCriterion("DelFlag >=", value, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagLessThan(Integer value) {
			addCriterion("DelFlag <", value, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagLessThanOrEqualTo(Integer value) {
			addCriterion("DelFlag <=", value, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagIn(List<Integer> values) {
			addCriterion("DelFlag in", values, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagNotIn(List<Integer> values) {
			addCriterion("DelFlag not in", values, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagBetween(Integer value1, Integer value2) {
			addCriterion("DelFlag between", value1, value2, "delflag");
			return (Criteria) this;
		}

		public Criteria andDelflagNotBetween(Integer value1, Integer value2) {
			addCriterion("DelFlag not between", value1, value2, "delflag");
			return (Criteria) this;
		}

		public Criteria andUpdatebyIsNull() {
			addCriterion("UpdateBy is null");
			return (Criteria) this;
		}

		public Criteria andUpdatebyIsNotNull() {
			addCriterion("UpdateBy is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatebyEqualTo(Long value) {
			addCriterion("UpdateBy =", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyNotEqualTo(Long value) {
			addCriterion("UpdateBy <>", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyGreaterThan(Long value) {
			addCriterion("UpdateBy >", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyGreaterThanOrEqualTo(Long value) {
			addCriterion("UpdateBy >=", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyLessThan(Long value) {
			addCriterion("UpdateBy <", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyLessThanOrEqualTo(Long value) {
			addCriterion("UpdateBy <=", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyIn(List<Long> values) {
			addCriterion("UpdateBy in", values, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyNotIn(List<Long> values) {
			addCriterion("UpdateBy not in", values, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyBetween(Long value1, Long value2) {
			addCriterion("UpdateBy between", value1, value2, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyNotBetween(Long value1, Long value2) {
			addCriterion("UpdateBy not between", value1, value2, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNull() {
			addCriterion("UpdateTime is null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNotNull() {
			addCriterion("UpdateTime is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeEqualTo(Date value) {
			addCriterion("UpdateTime =", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotEqualTo(Date value) {
			addCriterion("UpdateTime <>", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThan(Date value) {
			addCriterion("UpdateTime >", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UpdateTime >=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThan(Date value) {
			addCriterion("UpdateTime <", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
			addCriterion("UpdateTime <=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIn(List<Date> values) {
			addCriterion("UpdateTime in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotIn(List<Date> values) {
			addCriterion("UpdateTime not in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeBetween(Date value1, Date value2) {
			addCriterion("UpdateTime between", value1, value2, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
			addCriterion("UpdateTime not between", value1, value2, "updatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table userbodysize
	 * @mbg.generated  Thu Apr 13 21:33:56 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userbodysize
     *
     * @mbggenerated do_not_delete_during_merge Fri Feb 17 09:21:29 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}