package com.gafker.manage.pojo;

import java.util.Date;

public class Familydict {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familydict.id
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familydict.NameCn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String namecn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familydict.NameEn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String nameen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familydict.Meaning
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String meaning;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familydict.Meandetail
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String meandetail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familydict.WebRef
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String webref;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familydict.UseTimes
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Long usetimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familydict.CreateBy
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Long createby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familydict.CreateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familydict.UpdateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Date updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familydict.id
	 * @return  the value of familydict.id
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familydict.id
	 * @param id  the value for familydict.id
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familydict.NameCn
	 * @return  the value of familydict.NameCn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getNamecn() {
		return namecn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familydict.NameCn
	 * @param namecn  the value for familydict.NameCn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setNamecn(String namecn) {
		this.namecn = namecn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familydict.NameEn
	 * @return  the value of familydict.NameEn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getNameen() {
		return nameen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familydict.NameEn
	 * @param nameen  the value for familydict.NameEn
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setNameen(String nameen) {
		this.nameen = nameen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familydict.Meaning
	 * @return  the value of familydict.Meaning
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getMeaning() {
		return meaning;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familydict.Meaning
	 * @param meaning  the value for familydict.Meaning
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setMeaning(String meaning) {
		this.meaning = meaning;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familydict.Meandetail
	 * @return  the value of familydict.Meandetail
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getMeandetail() {
		return meandetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familydict.Meandetail
	 * @param meandetail  the value for familydict.Meandetail
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setMeandetail(String meandetail) {
		this.meandetail = meandetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familydict.WebRef
	 * @return  the value of familydict.WebRef
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getWebref() {
		return webref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familydict.WebRef
	 * @param webref  the value for familydict.WebRef
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setWebref(String webref) {
		this.webref = webref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familydict.UseTimes
	 * @return  the value of familydict.UseTimes
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Long getUsetimes() {
		return usetimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familydict.UseTimes
	 * @param usetimes  the value for familydict.UseTimes
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setUsetimes(Long usetimes) {
		this.usetimes = usetimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familydict.CreateBy
	 * @return  the value of familydict.CreateBy
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Long getCreateby() {
		return createby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familydict.CreateBy
	 * @param createby  the value for familydict.CreateBy
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setCreateby(Long createby) {
		this.createby = createby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familydict.CreateTime
	 * @return  the value of familydict.CreateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familydict.CreateTime
	 * @param createtime  the value for familydict.CreateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familydict.UpdateTime
	 * @return  the value of familydict.UpdateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familydict.UpdateTime
	 * @param updatetime  the value for familydict.UpdateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}
}