package com.gafker.manage.pojo;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.Size;

public class Familynews implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 7005184352450423946L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column familynews.id
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column familynews.NameEn
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    private String nameen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column familynews.NameCn
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    @Size(min=1,message="请输入收藏标题")
    private String namecn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column familynews.CateLog_type
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    @Size(min=1,message="请设置收藏类型")
    private String catelogType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column familynews.Url_address
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    @Size(min=1,message="访问地址不能为空")
    private String urlAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column familynews.Content
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    @Size(min=1,message="请记录收藏网址所讲的内容")
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column familynews.Star
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    private Long star;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column familynews.Idx
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    private Integer idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column familynews.WebUrls
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    private String weburls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column familynews.AdsIds_fk
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    private String adsidsFk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column familynews.Parent_id
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column familynews.Del_status
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    private Integer delStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column familynews.Create_by
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column familynews.Create_time
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column familynews.id
     *
     * @return the value of familynews.id
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column familynews.id
     *
     * @param id the value for familynews.id
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column familynews.NameEn
     *
     * @return the value of familynews.NameEn
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public String getNameen() {
        return nameen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column familynews.NameEn
     *
     * @param nameen the value for familynews.NameEn
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public void setNameen(String nameen) {
        this.nameen = nameen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column familynews.NameCn
     *
     * @return the value of familynews.NameCn
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public String getNamecn() {
        return namecn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column familynews.NameCn
     *
     * @param namecn the value for familynews.NameCn
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public void setNamecn(String namecn) {
        this.namecn = namecn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column familynews.CateLog_type
     *
     * @return the value of familynews.CateLog_type
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public String getCatelogType() {
        return catelogType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column familynews.CateLog_type
     *
     * @param catelogType the value for familynews.CateLog_type
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public void setCatelogType(String catelogType) {
        this.catelogType = catelogType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column familynews.Url_address
     *
     * @return the value of familynews.Url_address
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public String getUrlAddress() {
        return urlAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column familynews.Url_address
     *
     * @param urlAddress the value for familynews.Url_address
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public void setUrlAddress(String urlAddress) {
        this.urlAddress = urlAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column familynews.Content
     *
     * @return the value of familynews.Content
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column familynews.Content
     *
     * @param content the value for familynews.Content
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column familynews.Star
     *
     * @return the value of familynews.Star
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public Long getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column familynews.Star
     *
     * @param star the value for familynews.Star
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public void setStar(Long star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column familynews.Idx
     *
     * @return the value of familynews.Idx
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column familynews.Idx
     *
     * @param idx the value for familynews.Idx
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column familynews.WebUrls
     *
     * @return the value of familynews.WebUrls
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public String getWeburls() {
        return weburls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column familynews.WebUrls
     *
     * @param weburls the value for familynews.WebUrls
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public void setWeburls(String weburls) {
        this.weburls = weburls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column familynews.AdsIds_fk
     *
     * @return the value of familynews.AdsIds_fk
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public String getAdsidsFk() {
        return adsidsFk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column familynews.AdsIds_fk
     *
     * @param adsidsFk the value for familynews.AdsIds_fk
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public void setAdsidsFk(String adsidsFk) {
        this.adsidsFk = adsidsFk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column familynews.Parent_id
     *
     * @return the value of familynews.Parent_id
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column familynews.Parent_id
     *
     * @param parentId the value for familynews.Parent_id
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column familynews.Del_status
     *
     * @return the value of familynews.Del_status
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public Integer getDelStatus() {
        return delStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column familynews.Del_status
     *
     * @param delStatus the value for familynews.Del_status
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public void setDelStatus(Integer delStatus) {
        this.delStatus = delStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column familynews.Create_by
     *
     * @return the value of familynews.Create_by
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column familynews.Create_by
     *
     * @param createBy the value for familynews.Create_by
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column familynews.Create_time
     *
     * @return the value of familynews.Create_time
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column familynews.Create_time
     *
     * @param createTime the value for familynews.Create_time
     *
     * @mbg.generated Tue Mar 21 11:41:48 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}