package com.gafker.manage.pojo;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;

import org.springframework.format.annotation.DateTimeFormat;

public class Familyproduct implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -1649181242661850482L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.id
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.UstringId
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private String ustringid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.NameEn
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private String nameen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.NameCn
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	@NotNull(message = "农产品名称不能为空！")
	private String namecn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.Idx
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private Integer idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.ProductKinds
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private Integer productkinds;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.ProductCatelog
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private Integer productcatelog;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.ProductLevels
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private Integer productlevels;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.PricesObj
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private String pricesobj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.DefaultImages
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private String defaultimages;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.ImagesListObj
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private String imageslistobj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.Description
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.QrCode
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private String qrcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.QrTracea
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private String qrtracea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.WebUrls
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private String weburls;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.AdsIds__fk
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private String adsidsFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.OnShelvesTime
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date onshelvestime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.ProductDate
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date productdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.ProductStatus
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private Integer productstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.Family_fk
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private Long familyFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.ProductStar
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private Double productstar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.TraceabilityStar
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private Double traceabilitystar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.CreateTime
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.CreateBy
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private Long createby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.UpdateTime
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private Date updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column familyproduct.UpdateBy
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	private Long updateby;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.id
	 * @return  the value of familyproduct.id
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.id
	 * @param id  the value for familyproduct.id
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.UstringId
	 * @return  the value of familyproduct.UstringId
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public String getUstringid() {
		return ustringid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.UstringId
	 * @param ustringid  the value for familyproduct.UstringId
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setUstringid(String ustringid) {
		this.ustringid = ustringid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.NameEn
	 * @return  the value of familyproduct.NameEn
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public String getNameen() {
		return nameen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.NameEn
	 * @param nameen  the value for familyproduct.NameEn
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setNameen(String nameen) {
		this.nameen = nameen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.NameCn
	 * @return  the value of familyproduct.NameCn
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public String getNamecn() {
		return namecn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.NameCn
	 * @param namecn  the value for familyproduct.NameCn
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setNamecn(String namecn) {
		this.namecn = namecn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.Idx
	 * @return  the value of familyproduct.Idx
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public Integer getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.Idx
	 * @param idx  the value for familyproduct.Idx
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.ProductKinds
	 * @return  the value of familyproduct.ProductKinds
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public Integer getProductkinds() {
		return productkinds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.ProductKinds
	 * @param productkinds  the value for familyproduct.ProductKinds
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setProductkinds(Integer productkinds) {
		this.productkinds = productkinds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.ProductCatelog
	 * @return  the value of familyproduct.ProductCatelog
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public Integer getProductcatelog() {
		return productcatelog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.ProductCatelog
	 * @param productcatelog  the value for familyproduct.ProductCatelog
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setProductcatelog(Integer productcatelog) {
		this.productcatelog = productcatelog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.ProductLevels
	 * @return  the value of familyproduct.ProductLevels
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public Integer getProductlevels() {
		return productlevels;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.ProductLevels
	 * @param productlevels  the value for familyproduct.ProductLevels
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setProductlevels(Integer productlevels) {
		this.productlevels = productlevels;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.PricesObj
	 * @return  the value of familyproduct.PricesObj
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public String getPricesobj() {
		return pricesobj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.PricesObj
	 * @param pricesobj  the value for familyproduct.PricesObj
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setPricesobj(String pricesobj) {
		this.pricesobj = pricesobj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.DefaultImages
	 * @return  the value of familyproduct.DefaultImages
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public String getDefaultimages() {
		return defaultimages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.DefaultImages
	 * @param defaultimages  the value for familyproduct.DefaultImages
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setDefaultimages(String defaultimages) {
		this.defaultimages = defaultimages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.ImagesListObj
	 * @return  the value of familyproduct.ImagesListObj
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public String getImageslistobj() {
		return imageslistobj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.ImagesListObj
	 * @param imageslistobj  the value for familyproduct.ImagesListObj
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setImageslistobj(String imageslistobj) {
		this.imageslistobj = imageslistobj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.Description
	 * @return  the value of familyproduct.Description
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.Description
	 * @param description  the value for familyproduct.Description
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.QrCode
	 * @return  the value of familyproduct.QrCode
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public String getQrcode() {
		return qrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.QrCode
	 * @param qrcode  the value for familyproduct.QrCode
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setQrcode(String qrcode) {
		this.qrcode = qrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.QrTracea
	 * @return  the value of familyproduct.QrTracea
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public String getQrtracea() {
		return qrtracea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.QrTracea
	 * @param qrtracea  the value for familyproduct.QrTracea
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setQrtracea(String qrtracea) {
		this.qrtracea = qrtracea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.WebUrls
	 * @return  the value of familyproduct.WebUrls
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public String getWeburls() {
		return weburls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.WebUrls
	 * @param weburls  the value for familyproduct.WebUrls
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setWeburls(String weburls) {
		this.weburls = weburls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.AdsIds__fk
	 * @return  the value of familyproduct.AdsIds__fk
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public String getAdsidsFk() {
		return adsidsFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.AdsIds__fk
	 * @param adsidsFk  the value for familyproduct.AdsIds__fk
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setAdsidsFk(String adsidsFk) {
		this.adsidsFk = adsidsFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.OnShelvesTime
	 * @return  the value of familyproduct.OnShelvesTime
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public Date getOnshelvestime() {
		return onshelvestime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.OnShelvesTime
	 * @param onshelvestime  the value for familyproduct.OnShelvesTime
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setOnshelvestime(Date onshelvestime) {
		this.onshelvestime = onshelvestime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.ProductDate
	 * @return  the value of familyproduct.ProductDate
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public Date getProductdate() {
		return productdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.ProductDate
	 * @param productdate  the value for familyproduct.ProductDate
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setProductdate(Date productdate) {
		this.productdate = productdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.ProductStatus
	 * @return  the value of familyproduct.ProductStatus
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public Integer getProductstatus() {
		return productstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.ProductStatus
	 * @param productstatus  the value for familyproduct.ProductStatus
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setProductstatus(Integer productstatus) {
		this.productstatus = productstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.Family_fk
	 * @return  the value of familyproduct.Family_fk
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public Long getFamilyFk() {
		return familyFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.Family_fk
	 * @param familyFk  the value for familyproduct.Family_fk
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setFamilyFk(Long familyFk) {
		this.familyFk = familyFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.ProductStar
	 * @return  the value of familyproduct.ProductStar
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public Double getProductstar() {
		return productstar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.ProductStar
	 * @param productstar  the value for familyproduct.ProductStar
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setProductstar(Double productstar) {
		this.productstar = productstar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.TraceabilityStar
	 * @return  the value of familyproduct.TraceabilityStar
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public Double getTraceabilitystar() {
		return traceabilitystar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.TraceabilityStar
	 * @param traceabilitystar  the value for familyproduct.TraceabilityStar
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setTraceabilitystar(Double traceabilitystar) {
		this.traceabilitystar = traceabilitystar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.CreateTime
	 * @return  the value of familyproduct.CreateTime
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.CreateTime
	 * @param createtime  the value for familyproduct.CreateTime
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.CreateBy
	 * @return  the value of familyproduct.CreateBy
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public Long getCreateby() {
		return createby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.CreateBy
	 * @param createby  the value for familyproduct.CreateBy
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setCreateby(Long createby) {
		this.createby = createby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.UpdateTime
	 * @return  the value of familyproduct.UpdateTime
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.UpdateTime
	 * @param updatetime  the value for familyproduct.UpdateTime
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column familyproduct.UpdateBy
	 * @return  the value of familyproduct.UpdateBy
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public Long getUpdateby() {
		return updateby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column familyproduct.UpdateBy
	 * @param updateby  the value for familyproduct.UpdateBy
	 * @mbggenerated  Wed Mar 08 10:59:12 CST 2017
	 */
	public void setUpdateby(Long updateby) {
		this.updateby = updateby;
	}
}