package com.gafker.manage.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FamilyworkhelpExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table familyworkhelp
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table familyworkhelp
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table familyworkhelp
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyworkhelp
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public FamilyworkhelpExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyworkhelp
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyworkhelp
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyworkhelp
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyworkhelp
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyworkhelp
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyworkhelp
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyworkhelp
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyworkhelp
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyworkhelp
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyworkhelp
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table familyworkhelp
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUstringidIsNull() {
			addCriterion("UstringId is null");
			return (Criteria) this;
		}

		public Criteria andUstringidIsNotNull() {
			addCriterion("UstringId is not null");
			return (Criteria) this;
		}

		public Criteria andUstringidEqualTo(String value) {
			addCriterion("UstringId =", value, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidNotEqualTo(String value) {
			addCriterion("UstringId <>", value, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidGreaterThan(String value) {
			addCriterion("UstringId >", value, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidGreaterThanOrEqualTo(String value) {
			addCriterion("UstringId >=", value, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidLessThan(String value) {
			addCriterion("UstringId <", value, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidLessThanOrEqualTo(String value) {
			addCriterion("UstringId <=", value, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidLike(String value) {
			addCriterion("UstringId like", value, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidNotLike(String value) {
			addCriterion("UstringId not like", value, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidIn(List<String> values) {
			addCriterion("UstringId in", values, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidNotIn(List<String> values) {
			addCriterion("UstringId not in", values, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidBetween(String value1, String value2) {
			addCriterion("UstringId between", value1, value2, "ustringid");
			return (Criteria) this;
		}

		public Criteria andUstringidNotBetween(String value1, String value2) {
			addCriterion("UstringId not between", value1, value2, "ustringid");
			return (Criteria) this;
		}

		public Criteria andNameenIsNull() {
			addCriterion("NameEn is null");
			return (Criteria) this;
		}

		public Criteria andNameenIsNotNull() {
			addCriterion("NameEn is not null");
			return (Criteria) this;
		}

		public Criteria andNameenEqualTo(String value) {
			addCriterion("NameEn =", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenNotEqualTo(String value) {
			addCriterion("NameEn <>", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenGreaterThan(String value) {
			addCriterion("NameEn >", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenGreaterThanOrEqualTo(String value) {
			addCriterion("NameEn >=", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenLessThan(String value) {
			addCriterion("NameEn <", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenLessThanOrEqualTo(String value) {
			addCriterion("NameEn <=", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenLike(String value) {
			addCriterion("NameEn like", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenNotLike(String value) {
			addCriterion("NameEn not like", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenIn(List<String> values) {
			addCriterion("NameEn in", values, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenNotIn(List<String> values) {
			addCriterion("NameEn not in", values, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenBetween(String value1, String value2) {
			addCriterion("NameEn between", value1, value2, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenNotBetween(String value1, String value2) {
			addCriterion("NameEn not between", value1, value2, "nameen");
			return (Criteria) this;
		}

		public Criteria andNamecnIsNull() {
			addCriterion("NameCn is null");
			return (Criteria) this;
		}

		public Criteria andNamecnIsNotNull() {
			addCriterion("NameCn is not null");
			return (Criteria) this;
		}

		public Criteria andNamecnEqualTo(String value) {
			addCriterion("NameCn =", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnNotEqualTo(String value) {
			addCriterion("NameCn <>", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnGreaterThan(String value) {
			addCriterion("NameCn >", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnGreaterThanOrEqualTo(String value) {
			addCriterion("NameCn >=", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnLessThan(String value) {
			addCriterion("NameCn <", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnLessThanOrEqualTo(String value) {
			addCriterion("NameCn <=", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnLike(String value) {
			addCriterion("NameCn like", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnNotLike(String value) {
			addCriterion("NameCn not like", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnIn(List<String> values) {
			addCriterion("NameCn in", values, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnNotIn(List<String> values) {
			addCriterion("NameCn not in", values, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnBetween(String value1, String value2) {
			addCriterion("NameCn between", value1, value2, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnNotBetween(String value1, String value2) {
			addCriterion("NameCn not between", value1, value2, "namecn");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("Title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("Title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("Title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("Title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("Title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("Title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("Title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("Title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("Title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("Title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("Title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("Title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("Title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("Title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("Content is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("Content is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("Content =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("Content <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("Content >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("Content >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("Content <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("Content <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("Content like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("Content not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("Content in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("Content not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("Content between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("Content not between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andHelptypeIsNull() {
			addCriterion("HelpType is null");
			return (Criteria) this;
		}

		public Criteria andHelptypeIsNotNull() {
			addCriterion("HelpType is not null");
			return (Criteria) this;
		}

		public Criteria andHelptypeEqualTo(Integer value) {
			addCriterion("HelpType =", value, "helptype");
			return (Criteria) this;
		}

		public Criteria andHelptypeNotEqualTo(Integer value) {
			addCriterion("HelpType <>", value, "helptype");
			return (Criteria) this;
		}

		public Criteria andHelptypeGreaterThan(Integer value) {
			addCriterion("HelpType >", value, "helptype");
			return (Criteria) this;
		}

		public Criteria andHelptypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("HelpType >=", value, "helptype");
			return (Criteria) this;
		}

		public Criteria andHelptypeLessThan(Integer value) {
			addCriterion("HelpType <", value, "helptype");
			return (Criteria) this;
		}

		public Criteria andHelptypeLessThanOrEqualTo(Integer value) {
			addCriterion("HelpType <=", value, "helptype");
			return (Criteria) this;
		}

		public Criteria andHelptypeIn(List<Integer> values) {
			addCriterion("HelpType in", values, "helptype");
			return (Criteria) this;
		}

		public Criteria andHelptypeNotIn(List<Integer> values) {
			addCriterion("HelpType not in", values, "helptype");
			return (Criteria) this;
		}

		public Criteria andHelptypeBetween(Integer value1, Integer value2) {
			addCriterion("HelpType between", value1, value2, "helptype");
			return (Criteria) this;
		}

		public Criteria andHelptypeNotBetween(Integer value1, Integer value2) {
			addCriterion("HelpType not between", value1, value2, "helptype");
			return (Criteria) this;
		}

		public Criteria andMediatypeIsNull() {
			addCriterion("MediaType is null");
			return (Criteria) this;
		}

		public Criteria andMediatypeIsNotNull() {
			addCriterion("MediaType is not null");
			return (Criteria) this;
		}

		public Criteria andMediatypeEqualTo(Integer value) {
			addCriterion("MediaType =", value, "mediatype");
			return (Criteria) this;
		}

		public Criteria andMediatypeNotEqualTo(Integer value) {
			addCriterion("MediaType <>", value, "mediatype");
			return (Criteria) this;
		}

		public Criteria andMediatypeGreaterThan(Integer value) {
			addCriterion("MediaType >", value, "mediatype");
			return (Criteria) this;
		}

		public Criteria andMediatypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("MediaType >=", value, "mediatype");
			return (Criteria) this;
		}

		public Criteria andMediatypeLessThan(Integer value) {
			addCriterion("MediaType <", value, "mediatype");
			return (Criteria) this;
		}

		public Criteria andMediatypeLessThanOrEqualTo(Integer value) {
			addCriterion("MediaType <=", value, "mediatype");
			return (Criteria) this;
		}

		public Criteria andMediatypeIn(List<Integer> values) {
			addCriterion("MediaType in", values, "mediatype");
			return (Criteria) this;
		}

		public Criteria andMediatypeNotIn(List<Integer> values) {
			addCriterion("MediaType not in", values, "mediatype");
			return (Criteria) this;
		}

		public Criteria andMediatypeBetween(Integer value1, Integer value2) {
			addCriterion("MediaType between", value1, value2, "mediatype");
			return (Criteria) this;
		}

		public Criteria andMediatypeNotBetween(Integer value1, Integer value2) {
			addCriterion("MediaType not between", value1, value2, "mediatype");
			return (Criteria) this;
		}

		public Criteria andIdxIsNull() {
			addCriterion("Idx is null");
			return (Criteria) this;
		}

		public Criteria andIdxIsNotNull() {
			addCriterion("Idx is not null");
			return (Criteria) this;
		}

		public Criteria andIdxEqualTo(Integer value) {
			addCriterion("Idx =", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxNotEqualTo(Integer value) {
			addCriterion("Idx <>", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxGreaterThan(Integer value) {
			addCriterion("Idx >", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxGreaterThanOrEqualTo(Integer value) {
			addCriterion("Idx >=", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxLessThan(Integer value) {
			addCriterion("Idx <", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxLessThanOrEqualTo(Integer value) {
			addCriterion("Idx <=", value, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxIn(List<Integer> values) {
			addCriterion("Idx in", values, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxNotIn(List<Integer> values) {
			addCriterion("Idx not in", values, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxBetween(Integer value1, Integer value2) {
			addCriterion("Idx between", value1, value2, "idx");
			return (Criteria) this;
		}

		public Criteria andIdxNotBetween(Integer value1, Integer value2) {
			addCriterion("Idx not between", value1, value2, "idx");
			return (Criteria) this;
		}

		public Criteria andWeburlsIsNull() {
			addCriterion("WebUrls is null");
			return (Criteria) this;
		}

		public Criteria andWeburlsIsNotNull() {
			addCriterion("WebUrls is not null");
			return (Criteria) this;
		}

		public Criteria andWeburlsEqualTo(String value) {
			addCriterion("WebUrls =", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsNotEqualTo(String value) {
			addCriterion("WebUrls <>", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsGreaterThan(String value) {
			addCriterion("WebUrls >", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsGreaterThanOrEqualTo(String value) {
			addCriterion("WebUrls >=", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsLessThan(String value) {
			addCriterion("WebUrls <", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsLessThanOrEqualTo(String value) {
			addCriterion("WebUrls <=", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsLike(String value) {
			addCriterion("WebUrls like", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsNotLike(String value) {
			addCriterion("WebUrls not like", value, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsIn(List<String> values) {
			addCriterion("WebUrls in", values, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsNotIn(List<String> values) {
			addCriterion("WebUrls not in", values, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsBetween(String value1, String value2) {
			addCriterion("WebUrls between", value1, value2, "weburls");
			return (Criteria) this;
		}

		public Criteria andWeburlsNotBetween(String value1, String value2) {
			addCriterion("WebUrls not between", value1, value2, "weburls");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkIsNull() {
			addCriterion("AdsIds_fk is null");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkIsNotNull() {
			addCriterion("AdsIds_fk is not null");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkEqualTo(String value) {
			addCriterion("AdsIds_fk =", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkNotEqualTo(String value) {
			addCriterion("AdsIds_fk <>", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkGreaterThan(String value) {
			addCriterion("AdsIds_fk >", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkGreaterThanOrEqualTo(String value) {
			addCriterion("AdsIds_fk >=", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkLessThan(String value) {
			addCriterion("AdsIds_fk <", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkLessThanOrEqualTo(String value) {
			addCriterion("AdsIds_fk <=", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkLike(String value) {
			addCriterion("AdsIds_fk like", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkNotLike(String value) {
			addCriterion("AdsIds_fk not like", value, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkIn(List<String> values) {
			addCriterion("AdsIds_fk in", values, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkNotIn(List<String> values) {
			addCriterion("AdsIds_fk not in", values, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkBetween(String value1, String value2) {
			addCriterion("AdsIds_fk between", value1, value2, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andAdsidsFkNotBetween(String value1, String value2) {
			addCriterion("AdsIds_fk not between", value1, value2, "adsidsFk");
			return (Criteria) this;
		}

		public Criteria andCreatebyIsNull() {
			addCriterion("CreateBy is null");
			return (Criteria) this;
		}

		public Criteria andCreatebyIsNotNull() {
			addCriterion("CreateBy is not null");
			return (Criteria) this;
		}

		public Criteria andCreatebyEqualTo(Long value) {
			addCriterion("CreateBy =", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyNotEqualTo(Long value) {
			addCriterion("CreateBy <>", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyGreaterThan(Long value) {
			addCriterion("CreateBy >", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyGreaterThanOrEqualTo(Long value) {
			addCriterion("CreateBy >=", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyLessThan(Long value) {
			addCriterion("CreateBy <", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyLessThanOrEqualTo(Long value) {
			addCriterion("CreateBy <=", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyIn(List<Long> values) {
			addCriterion("CreateBy in", values, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyNotIn(List<Long> values) {
			addCriterion("CreateBy not in", values, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyBetween(Long value1, Long value2) {
			addCriterion("CreateBy between", value1, value2, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyNotBetween(Long value1, Long value2) {
			addCriterion("CreateBy not between", value1, value2, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNull() {
			addCriterion("CreateTime is null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNotNull() {
			addCriterion("CreateTime is not null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeEqualTo(Date value) {
			addCriterion("CreateTime =", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotEqualTo(Date value) {
			addCriterion("CreateTime <>", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThan(Date value) {
			addCriterion("CreateTime >", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CreateTime >=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThan(Date value) {
			addCriterion("CreateTime <", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
			addCriterion("CreateTime <=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIn(List<Date> values) {
			addCriterion("CreateTime in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotIn(List<Date> values) {
			addCriterion("CreateTime not in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeBetween(Date value1, Date value2) {
			addCriterion("CreateTime between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
			addCriterion("CreateTime not between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andUpdatebyIsNull() {
			addCriterion("UpdateBy is null");
			return (Criteria) this;
		}

		public Criteria andUpdatebyIsNotNull() {
			addCriterion("UpdateBy is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatebyEqualTo(Long value) {
			addCriterion("UpdateBy =", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyNotEqualTo(Long value) {
			addCriterion("UpdateBy <>", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyGreaterThan(Long value) {
			addCriterion("UpdateBy >", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyGreaterThanOrEqualTo(Long value) {
			addCriterion("UpdateBy >=", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyLessThan(Long value) {
			addCriterion("UpdateBy <", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyLessThanOrEqualTo(Long value) {
			addCriterion("UpdateBy <=", value, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyIn(List<Long> values) {
			addCriterion("UpdateBy in", values, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyNotIn(List<Long> values) {
			addCriterion("UpdateBy not in", values, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyBetween(Long value1, Long value2) {
			addCriterion("UpdateBy between", value1, value2, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatebyNotBetween(Long value1, Long value2) {
			addCriterion("UpdateBy not between", value1, value2, "updateby");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNull() {
			addCriterion("UpdateTime is null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNotNull() {
			addCriterion("UpdateTime is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeEqualTo(Date value) {
			addCriterion("UpdateTime =", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotEqualTo(Date value) {
			addCriterion("UpdateTime <>", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThan(Date value) {
			addCriterion("UpdateTime >", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UpdateTime >=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThan(Date value) {
			addCriterion("UpdateTime <", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
			addCriterion("UpdateTime <=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIn(List<Date> values) {
			addCriterion("UpdateTime in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotIn(List<Date> values) {
			addCriterion("UpdateTime not in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeBetween(Date value1, Date value2) {
			addCriterion("UpdateTime between", value1, value2, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
			addCriterion("UpdateTime not between", value1, value2, "updatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table familyworkhelp
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table familyworkhelp
     *
     * @mbggenerated do_not_delete_during_merge Fri Feb 17 09:21:29 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}