package com.gafker.manage.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FamilydictExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table familydict
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table familydict
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table familydict
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familydict
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public FamilydictExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familydict
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familydict
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familydict
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familydict
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familydict
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familydict
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familydict
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familydict
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familydict
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familydict
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table familydict
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNamecnIsNull() {
			addCriterion("NameCn is null");
			return (Criteria) this;
		}

		public Criteria andNamecnIsNotNull() {
			addCriterion("NameCn is not null");
			return (Criteria) this;
		}

		public Criteria andNamecnEqualTo(String value) {
			addCriterion("NameCn =", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnNotEqualTo(String value) {
			addCriterion("NameCn <>", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnGreaterThan(String value) {
			addCriterion("NameCn >", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnGreaterThanOrEqualTo(String value) {
			addCriterion("NameCn >=", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnLessThan(String value) {
			addCriterion("NameCn <", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnLessThanOrEqualTo(String value) {
			addCriterion("NameCn <=", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnLike(String value) {
			addCriterion("NameCn like", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnNotLike(String value) {
			addCriterion("NameCn not like", value, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnIn(List<String> values) {
			addCriterion("NameCn in", values, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnNotIn(List<String> values) {
			addCriterion("NameCn not in", values, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnBetween(String value1, String value2) {
			addCriterion("NameCn between", value1, value2, "namecn");
			return (Criteria) this;
		}

		public Criteria andNamecnNotBetween(String value1, String value2) {
			addCriterion("NameCn not between", value1, value2, "namecn");
			return (Criteria) this;
		}

		public Criteria andNameenIsNull() {
			addCriterion("NameEn is null");
			return (Criteria) this;
		}

		public Criteria andNameenIsNotNull() {
			addCriterion("NameEn is not null");
			return (Criteria) this;
		}

		public Criteria andNameenEqualTo(String value) {
			addCriterion("NameEn =", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenNotEqualTo(String value) {
			addCriterion("NameEn <>", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenGreaterThan(String value) {
			addCriterion("NameEn >", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenGreaterThanOrEqualTo(String value) {
			addCriterion("NameEn >=", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenLessThan(String value) {
			addCriterion("NameEn <", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenLessThanOrEqualTo(String value) {
			addCriterion("NameEn <=", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenLike(String value) {
			addCriterion("NameEn like", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenNotLike(String value) {
			addCriterion("NameEn not like", value, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenIn(List<String> values) {
			addCriterion("NameEn in", values, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenNotIn(List<String> values) {
			addCriterion("NameEn not in", values, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenBetween(String value1, String value2) {
			addCriterion("NameEn between", value1, value2, "nameen");
			return (Criteria) this;
		}

		public Criteria andNameenNotBetween(String value1, String value2) {
			addCriterion("NameEn not between", value1, value2, "nameen");
			return (Criteria) this;
		}

		public Criteria andMeaningIsNull() {
			addCriterion("Meaning is null");
			return (Criteria) this;
		}

		public Criteria andMeaningIsNotNull() {
			addCriterion("Meaning is not null");
			return (Criteria) this;
		}

		public Criteria andMeaningEqualTo(String value) {
			addCriterion("Meaning =", value, "meaning");
			return (Criteria) this;
		}

		public Criteria andMeaningNotEqualTo(String value) {
			addCriterion("Meaning <>", value, "meaning");
			return (Criteria) this;
		}

		public Criteria andMeaningGreaterThan(String value) {
			addCriterion("Meaning >", value, "meaning");
			return (Criteria) this;
		}

		public Criteria andMeaningGreaterThanOrEqualTo(String value) {
			addCriterion("Meaning >=", value, "meaning");
			return (Criteria) this;
		}

		public Criteria andMeaningLessThan(String value) {
			addCriterion("Meaning <", value, "meaning");
			return (Criteria) this;
		}

		public Criteria andMeaningLessThanOrEqualTo(String value) {
			addCriterion("Meaning <=", value, "meaning");
			return (Criteria) this;
		}

		public Criteria andMeaningLike(String value) {
			addCriterion("Meaning like", value, "meaning");
			return (Criteria) this;
		}

		public Criteria andMeaningNotLike(String value) {
			addCriterion("Meaning not like", value, "meaning");
			return (Criteria) this;
		}

		public Criteria andMeaningIn(List<String> values) {
			addCriterion("Meaning in", values, "meaning");
			return (Criteria) this;
		}

		public Criteria andMeaningNotIn(List<String> values) {
			addCriterion("Meaning not in", values, "meaning");
			return (Criteria) this;
		}

		public Criteria andMeaningBetween(String value1, String value2) {
			addCriterion("Meaning between", value1, value2, "meaning");
			return (Criteria) this;
		}

		public Criteria andMeaningNotBetween(String value1, String value2) {
			addCriterion("Meaning not between", value1, value2, "meaning");
			return (Criteria) this;
		}

		public Criteria andMeandetailIsNull() {
			addCriterion("Meandetail is null");
			return (Criteria) this;
		}

		public Criteria andMeandetailIsNotNull() {
			addCriterion("Meandetail is not null");
			return (Criteria) this;
		}

		public Criteria andMeandetailEqualTo(String value) {
			addCriterion("Meandetail =", value, "meandetail");
			return (Criteria) this;
		}

		public Criteria andMeandetailNotEqualTo(String value) {
			addCriterion("Meandetail <>", value, "meandetail");
			return (Criteria) this;
		}

		public Criteria andMeandetailGreaterThan(String value) {
			addCriterion("Meandetail >", value, "meandetail");
			return (Criteria) this;
		}

		public Criteria andMeandetailGreaterThanOrEqualTo(String value) {
			addCriterion("Meandetail >=", value, "meandetail");
			return (Criteria) this;
		}

		public Criteria andMeandetailLessThan(String value) {
			addCriterion("Meandetail <", value, "meandetail");
			return (Criteria) this;
		}

		public Criteria andMeandetailLessThanOrEqualTo(String value) {
			addCriterion("Meandetail <=", value, "meandetail");
			return (Criteria) this;
		}

		public Criteria andMeandetailLike(String value) {
			addCriterion("Meandetail like", value, "meandetail");
			return (Criteria) this;
		}

		public Criteria andMeandetailNotLike(String value) {
			addCriterion("Meandetail not like", value, "meandetail");
			return (Criteria) this;
		}

		public Criteria andMeandetailIn(List<String> values) {
			addCriterion("Meandetail in", values, "meandetail");
			return (Criteria) this;
		}

		public Criteria andMeandetailNotIn(List<String> values) {
			addCriterion("Meandetail not in", values, "meandetail");
			return (Criteria) this;
		}

		public Criteria andMeandetailBetween(String value1, String value2) {
			addCriterion("Meandetail between", value1, value2, "meandetail");
			return (Criteria) this;
		}

		public Criteria andMeandetailNotBetween(String value1, String value2) {
			addCriterion("Meandetail not between", value1, value2, "meandetail");
			return (Criteria) this;
		}

		public Criteria andWebrefIsNull() {
			addCriterion("WebRef is null");
			return (Criteria) this;
		}

		public Criteria andWebrefIsNotNull() {
			addCriterion("WebRef is not null");
			return (Criteria) this;
		}

		public Criteria andWebrefEqualTo(String value) {
			addCriterion("WebRef =", value, "webref");
			return (Criteria) this;
		}

		public Criteria andWebrefNotEqualTo(String value) {
			addCriterion("WebRef <>", value, "webref");
			return (Criteria) this;
		}

		public Criteria andWebrefGreaterThan(String value) {
			addCriterion("WebRef >", value, "webref");
			return (Criteria) this;
		}

		public Criteria andWebrefGreaterThanOrEqualTo(String value) {
			addCriterion("WebRef >=", value, "webref");
			return (Criteria) this;
		}

		public Criteria andWebrefLessThan(String value) {
			addCriterion("WebRef <", value, "webref");
			return (Criteria) this;
		}

		public Criteria andWebrefLessThanOrEqualTo(String value) {
			addCriterion("WebRef <=", value, "webref");
			return (Criteria) this;
		}

		public Criteria andWebrefLike(String value) {
			addCriterion("WebRef like", value, "webref");
			return (Criteria) this;
		}

		public Criteria andWebrefNotLike(String value) {
			addCriterion("WebRef not like", value, "webref");
			return (Criteria) this;
		}

		public Criteria andWebrefIn(List<String> values) {
			addCriterion("WebRef in", values, "webref");
			return (Criteria) this;
		}

		public Criteria andWebrefNotIn(List<String> values) {
			addCriterion("WebRef not in", values, "webref");
			return (Criteria) this;
		}

		public Criteria andWebrefBetween(String value1, String value2) {
			addCriterion("WebRef between", value1, value2, "webref");
			return (Criteria) this;
		}

		public Criteria andWebrefNotBetween(String value1, String value2) {
			addCriterion("WebRef not between", value1, value2, "webref");
			return (Criteria) this;
		}

		public Criteria andUsetimesIsNull() {
			addCriterion("UseTimes is null");
			return (Criteria) this;
		}

		public Criteria andUsetimesIsNotNull() {
			addCriterion("UseTimes is not null");
			return (Criteria) this;
		}

		public Criteria andUsetimesEqualTo(Long value) {
			addCriterion("UseTimes =", value, "usetimes");
			return (Criteria) this;
		}

		public Criteria andUsetimesNotEqualTo(Long value) {
			addCriterion("UseTimes <>", value, "usetimes");
			return (Criteria) this;
		}

		public Criteria andUsetimesGreaterThan(Long value) {
			addCriterion("UseTimes >", value, "usetimes");
			return (Criteria) this;
		}

		public Criteria andUsetimesGreaterThanOrEqualTo(Long value) {
			addCriterion("UseTimes >=", value, "usetimes");
			return (Criteria) this;
		}

		public Criteria andUsetimesLessThan(Long value) {
			addCriterion("UseTimes <", value, "usetimes");
			return (Criteria) this;
		}

		public Criteria andUsetimesLessThanOrEqualTo(Long value) {
			addCriterion("UseTimes <=", value, "usetimes");
			return (Criteria) this;
		}

		public Criteria andUsetimesIn(List<Long> values) {
			addCriterion("UseTimes in", values, "usetimes");
			return (Criteria) this;
		}

		public Criteria andUsetimesNotIn(List<Long> values) {
			addCriterion("UseTimes not in", values, "usetimes");
			return (Criteria) this;
		}

		public Criteria andUsetimesBetween(Long value1, Long value2) {
			addCriterion("UseTimes between", value1, value2, "usetimes");
			return (Criteria) this;
		}

		public Criteria andUsetimesNotBetween(Long value1, Long value2) {
			addCriterion("UseTimes not between", value1, value2, "usetimes");
			return (Criteria) this;
		}

		public Criteria andCreatebyIsNull() {
			addCriterion("CreateBy is null");
			return (Criteria) this;
		}

		public Criteria andCreatebyIsNotNull() {
			addCriterion("CreateBy is not null");
			return (Criteria) this;
		}

		public Criteria andCreatebyEqualTo(Long value) {
			addCriterion("CreateBy =", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyNotEqualTo(Long value) {
			addCriterion("CreateBy <>", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyGreaterThan(Long value) {
			addCriterion("CreateBy >", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyGreaterThanOrEqualTo(Long value) {
			addCriterion("CreateBy >=", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyLessThan(Long value) {
			addCriterion("CreateBy <", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyLessThanOrEqualTo(Long value) {
			addCriterion("CreateBy <=", value, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyIn(List<Long> values) {
			addCriterion("CreateBy in", values, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyNotIn(List<Long> values) {
			addCriterion("CreateBy not in", values, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyBetween(Long value1, Long value2) {
			addCriterion("CreateBy between", value1, value2, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatebyNotBetween(Long value1, Long value2) {
			addCriterion("CreateBy not between", value1, value2, "createby");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNull() {
			addCriterion("CreateTime is null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNotNull() {
			addCriterion("CreateTime is not null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeEqualTo(Date value) {
			addCriterion("CreateTime =", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotEqualTo(Date value) {
			addCriterion("CreateTime <>", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThan(Date value) {
			addCriterion("CreateTime >", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CreateTime >=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThan(Date value) {
			addCriterion("CreateTime <", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
			addCriterion("CreateTime <=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIn(List<Date> values) {
			addCriterion("CreateTime in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotIn(List<Date> values) {
			addCriterion("CreateTime not in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeBetween(Date value1, Date value2) {
			addCriterion("CreateTime between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
			addCriterion("CreateTime not between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNull() {
			addCriterion("UpdateTime is null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNotNull() {
			addCriterion("UpdateTime is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeEqualTo(Date value) {
			addCriterion("UpdateTime =", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotEqualTo(Date value) {
			addCriterion("UpdateTime <>", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThan(Date value) {
			addCriterion("UpdateTime >", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UpdateTime >=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThan(Date value) {
			addCriterion("UpdateTime <", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
			addCriterion("UpdateTime <=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIn(List<Date> values) {
			addCriterion("UpdateTime in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotIn(List<Date> values) {
			addCriterion("UpdateTime not in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeBetween(Date value1, Date value2) {
			addCriterion("UpdateTime between", value1, value2, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
			addCriterion("UpdateTime not between", value1, value2, "updatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table familydict
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table familydict
     *
     * @mbggenerated do_not_delete_during_merge Fri Feb 17 09:21:29 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}