package com.gafker.manage.pojo;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotBlank;

public class Happayteachersdays implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 2346398511353420051L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.Id
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.UstringId
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String ustringid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.Content
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	@NotBlank
	@Size(min = 6, max = 1000,message="祝福内容要6~1000个字！")
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.Teachers
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	@NotBlank(message="祝福要送给谁？")
	private String teachers;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.Students
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	@NotBlank(message="请让祝福人知道你的名！")
	private String students;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.GoodPoints
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Long goodpoints;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.IpAddress
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String ipaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.UserAgent
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String useragent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.Schools
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String schools;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.DayType
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer daytype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.IsShow
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer isshow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.ImagesPath
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String imagespath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.CreateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.UpdateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Date updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.CreateUser
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String createuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.UpdateUser
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String updateuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.MessagesKinds
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer messageskinds;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.MessageStatus
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer messagestatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.QrCode
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private String qrcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.MessagesId
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Long messagesid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.MessageSenderType
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer messagesendertype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.MessageReceiveType
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer messagereceivetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.MessageIdx
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Integer messageidx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.Sender
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Long sender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column happayteachersdays.Receiver
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	private Long receiver;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.Id
	 * @return  the value of happayteachersdays.Id
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.Id
	 * @param id  the value for happayteachersdays.Id
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.UstringId
	 * @return  the value of happayteachersdays.UstringId
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getUstringid() {
		return ustringid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.UstringId
	 * @param ustringid  the value for happayteachersdays.UstringId
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setUstringid(String ustringid) {
		this.ustringid = ustringid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.Content
	 * @return  the value of happayteachersdays.Content
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.Content
	 * @param content  the value for happayteachersdays.Content
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.Teachers
	 * @return  the value of happayteachersdays.Teachers
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getTeachers() {
		return teachers;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.Teachers
	 * @param teachers  the value for happayteachersdays.Teachers
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setTeachers(String teachers) {
		this.teachers = teachers;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.Students
	 * @return  the value of happayteachersdays.Students
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getStudents() {
		return students;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.Students
	 * @param students  the value for happayteachersdays.Students
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setStudents(String students) {
		this.students = students;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.GoodPoints
	 * @return  the value of happayteachersdays.GoodPoints
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Long getGoodpoints() {
		return goodpoints;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.GoodPoints
	 * @param goodpoints  the value for happayteachersdays.GoodPoints
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setGoodpoints(Long goodpoints) {
		this.goodpoints = goodpoints;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.IpAddress
	 * @return  the value of happayteachersdays.IpAddress
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getIpaddress() {
		return ipaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.IpAddress
	 * @param ipaddress  the value for happayteachersdays.IpAddress
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.UserAgent
	 * @return  the value of happayteachersdays.UserAgent
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getUseragent() {
		return useragent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.UserAgent
	 * @param useragent  the value for happayteachersdays.UserAgent
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setUseragent(String useragent) {
		this.useragent = useragent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.Schools
	 * @return  the value of happayteachersdays.Schools
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getSchools() {
		return schools;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.Schools
	 * @param schools  the value for happayteachersdays.Schools
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setSchools(String schools) {
		this.schools = schools;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.DayType
	 * @return  the value of happayteachersdays.DayType
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getDaytype() {
		return daytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.DayType
	 * @param daytype  the value for happayteachersdays.DayType
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setDaytype(Integer daytype) {
		this.daytype = daytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.IsShow
	 * @return  the value of happayteachersdays.IsShow
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getIsshow() {
		return isshow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.IsShow
	 * @param isshow  the value for happayteachersdays.IsShow
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setIsshow(Integer isshow) {
		this.isshow = isshow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.ImagesPath
	 * @return  the value of happayteachersdays.ImagesPath
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getImagespath() {
		return imagespath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.ImagesPath
	 * @param imagespath  the value for happayteachersdays.ImagesPath
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setImagespath(String imagespath) {
		this.imagespath = imagespath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.CreateTime
	 * @return  the value of happayteachersdays.CreateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.CreateTime
	 * @param createtime  the value for happayteachersdays.CreateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.UpdateTime
	 * @return  the value of happayteachersdays.UpdateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.UpdateTime
	 * @param updatetime  the value for happayteachersdays.UpdateTime
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.CreateUser
	 * @return  the value of happayteachersdays.CreateUser
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getCreateuser() {
		return createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.CreateUser
	 * @param createuser  the value for happayteachersdays.CreateUser
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.UpdateUser
	 * @return  the value of happayteachersdays.UpdateUser
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getUpdateuser() {
		return updateuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.UpdateUser
	 * @param updateuser  the value for happayteachersdays.UpdateUser
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.MessagesKinds
	 * @return  the value of happayteachersdays.MessagesKinds
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getMessageskinds() {
		return messageskinds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.MessagesKinds
	 * @param messageskinds  the value for happayteachersdays.MessagesKinds
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setMessageskinds(Integer messageskinds) {
		this.messageskinds = messageskinds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.MessageStatus
	 * @return  the value of happayteachersdays.MessageStatus
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getMessagestatus() {
		return messagestatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.MessageStatus
	 * @param messagestatus  the value for happayteachersdays.MessageStatus
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setMessagestatus(Integer messagestatus) {
		this.messagestatus = messagestatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.QrCode
	 * @return  the value of happayteachersdays.QrCode
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public String getQrcode() {
		return qrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.QrCode
	 * @param qrcode  the value for happayteachersdays.QrCode
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setQrcode(String qrcode) {
		this.qrcode = qrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.MessagesId
	 * @return  the value of happayteachersdays.MessagesId
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Long getMessagesid() {
		return messagesid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.MessagesId
	 * @param messagesid  the value for happayteachersdays.MessagesId
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setMessagesid(Long messagesid) {
		this.messagesid = messagesid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.MessageSenderType
	 * @return  the value of happayteachersdays.MessageSenderType
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getMessagesendertype() {
		return messagesendertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.MessageSenderType
	 * @param messagesendertype  the value for happayteachersdays.MessageSenderType
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setMessagesendertype(Integer messagesendertype) {
		this.messagesendertype = messagesendertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.MessageReceiveType
	 * @return  the value of happayteachersdays.MessageReceiveType
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getMessagereceivetype() {
		return messagereceivetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.MessageReceiveType
	 * @param messagereceivetype  the value for happayteachersdays.MessageReceiveType
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setMessagereceivetype(Integer messagereceivetype) {
		this.messagereceivetype = messagereceivetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.MessageIdx
	 * @return  the value of happayteachersdays.MessageIdx
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Integer getMessageidx() {
		return messageidx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.MessageIdx
	 * @param messageidx  the value for happayteachersdays.MessageIdx
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setMessageidx(Integer messageidx) {
		this.messageidx = messageidx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.Sender
	 * @return  the value of happayteachersdays.Sender
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Long getSender() {
		return sender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.Sender
	 * @param sender  the value for happayteachersdays.Sender
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setSender(Long sender) {
		this.sender = sender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column happayteachersdays.Receiver
	 * @return  the value of happayteachersdays.Receiver
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public Long getReceiver() {
		return receiver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column happayteachersdays.Receiver
	 * @param receiver  the value for happayteachersdays.Receiver
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	public void setReceiver(Long receiver) {
		this.receiver = receiver;
	}

	public Happayteachersdays() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Happayteachersdays(Long id, String content, String teachers, String students, Long goodpoints,
			String ipaddress, String useragent, String schools, Integer daytype, Integer isshow, String imagespath,
			Date createtime, Date updatetime, String createuser, String updateuser) {
		super();
		this.id = id;
		this.content = content;
		this.teachers = teachers;
		this.students = students;
		this.goodpoints = goodpoints;
		this.ipaddress = ipaddress;
		this.useragent = useragent;
		this.schools = schools;
		this.daytype = daytype;
		this.isshow = isshow;
		this.imagespath = imagespath;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.createuser = createuser;
		this.updateuser = updateuser;
	}
    
    
}