package com.gafker.manage.pojo;

import java.io.Serializable;
import java.util.Date;

public class Phoneseven  implements Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phoneseven.id
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phoneseven.NameEn
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	private String nameen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phoneseven.NameCn
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	private String namecn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phoneseven.PhoneSeven
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	private Long phoneseven;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phoneseven.Finished
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	private String finished;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phoneseven.StartPosition
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	private String startposition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phoneseven.GeoPosition
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	private String geoposition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phoneseven.Count
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	private Long count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phoneseven.Remarks
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phoneseven.Idx
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	private Integer idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phoneseven.WebUrls
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	private String weburls;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phoneseven.AdsIds_fk
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	private String adsidsFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phoneseven.Prefix_fk
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	private Long prefixFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phoneseven.UpdateTime
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	private Date updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phoneseven.UpdateBy
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	private Long updateby;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phoneseven.id
	 * @return  the value of phoneseven.id
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phoneseven.id
	 * @param id  the value for phoneseven.id
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phoneseven.NameEn
	 * @return  the value of phoneseven.NameEn
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public String getNameen() {
		return nameen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phoneseven.NameEn
	 * @param nameen  the value for phoneseven.NameEn
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public void setNameen(String nameen) {
		this.nameen = nameen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phoneseven.NameCn
	 * @return  the value of phoneseven.NameCn
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public String getNamecn() {
		return namecn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phoneseven.NameCn
	 * @param namecn  the value for phoneseven.NameCn
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public void setNamecn(String namecn) {
		this.namecn = namecn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phoneseven.PhoneSeven
	 * @return  the value of phoneseven.PhoneSeven
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public Long getPhoneseven() {
		return phoneseven;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phoneseven.PhoneSeven
	 * @param phoneseven  the value for phoneseven.PhoneSeven
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public void setPhoneseven(Long phoneseven) {
		this.phoneseven = phoneseven;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phoneseven.Finished
	 * @return  the value of phoneseven.Finished
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public String getFinished() {
		return finished;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phoneseven.Finished
	 * @param finished  the value for phoneseven.Finished
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public void setFinished(String finished) {
		this.finished = finished;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phoneseven.StartPosition
	 * @return  the value of phoneseven.StartPosition
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public String getStartposition() {
		return startposition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phoneseven.StartPosition
	 * @param startposition  the value for phoneseven.StartPosition
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public void setStartposition(String startposition) {
		this.startposition = startposition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phoneseven.GeoPosition
	 * @return  the value of phoneseven.GeoPosition
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public String getGeoposition() {
		return geoposition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phoneseven.GeoPosition
	 * @param geoposition  the value for phoneseven.GeoPosition
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public void setGeoposition(String geoposition) {
		this.geoposition = geoposition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phoneseven.Count
	 * @return  the value of phoneseven.Count
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public Long getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phoneseven.Count
	 * @param count  the value for phoneseven.Count
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public void setCount(Long count) {
		this.count = count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phoneseven.Remarks
	 * @return  the value of phoneseven.Remarks
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phoneseven.Remarks
	 * @param remarks  the value for phoneseven.Remarks
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phoneseven.Idx
	 * @return  the value of phoneseven.Idx
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public Integer getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phoneseven.Idx
	 * @param idx  the value for phoneseven.Idx
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phoneseven.WebUrls
	 * @return  the value of phoneseven.WebUrls
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public String getWeburls() {
		return weburls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phoneseven.WebUrls
	 * @param weburls  the value for phoneseven.WebUrls
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public void setWeburls(String weburls) {
		this.weburls = weburls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phoneseven.AdsIds_fk
	 * @return  the value of phoneseven.AdsIds_fk
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public String getAdsidsFk() {
		return adsidsFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phoneseven.AdsIds_fk
	 * @param adsidsFk  the value for phoneseven.AdsIds_fk
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public void setAdsidsFk(String adsidsFk) {
		this.adsidsFk = adsidsFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phoneseven.Prefix_fk
	 * @return  the value of phoneseven.Prefix_fk
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public Long getPrefixFk() {
		return prefixFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phoneseven.Prefix_fk
	 * @param prefixFk  the value for phoneseven.Prefix_fk
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public void setPrefixFk(Long prefixFk) {
		this.prefixFk = prefixFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phoneseven.UpdateTime
	 * @return  the value of phoneseven.UpdateTime
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phoneseven.UpdateTime
	 * @param updatetime  the value for phoneseven.UpdateTime
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phoneseven.UpdateBy
	 * @return  the value of phoneseven.UpdateBy
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public Long getUpdateby() {
		return updateby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phoneseven.UpdateBy
	 * @param updateby  the value for phoneseven.UpdateBy
	 * @mbg.generated  Sun Apr 23 20:19:45 CST 2017
	 */
	public void setUpdateby(Long updateby) {
		this.updateby = updateby;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 6785133465896406853L;
}