package com.gafker.manage.pojo;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotBlank;

public class SysDict implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -4454134883023206821L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.id
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.label_cn
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	private String labelCn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.label_en
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	private String labelEn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.value
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.type
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	@Size(min=1,message="至少要有一位")
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.description
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.sort
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	@Min(value = 0)
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.create_by
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.create_date
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.update_by
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	private String updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.update_date
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.remarks
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.del_flag
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	private String delFlag="0";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.use_position
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	private String usePosition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.parent_id
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	private Integer parentId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.id
	 * @return  the value of sys_dict.id
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.id
	 * @param id  the value for sys_dict.id
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.label_cn
	 * @return  the value of sys_dict.label_cn
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public String getLabelCn() {
		return labelCn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.label_cn
	 * @param labelCn  the value for sys_dict.label_cn
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public void setLabelCn(String labelCn) {
		this.labelCn = labelCn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.label_en
	 * @return  the value of sys_dict.label_en
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public String getLabelEn() {
		return labelEn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.label_en
	 * @param labelEn  the value for sys_dict.label_en
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public void setLabelEn(String labelEn) {
		this.labelEn = labelEn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.value
	 * @return  the value of sys_dict.value
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.value
	 * @param value  the value for sys_dict.value
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.type
	 * @return  the value of sys_dict.type
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.type
	 * @param type  the value for sys_dict.type
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.description
	 * @return  the value of sys_dict.description
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.description
	 * @param description  the value for sys_dict.description
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.sort
	 * @return  the value of sys_dict.sort
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.sort
	 * @param sort  the value for sys_dict.sort
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.create_by
	 * @return  the value of sys_dict.create_by
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.create_by
	 * @param createBy  the value for sys_dict.create_by
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.create_date
	 * @return  the value of sys_dict.create_date
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.create_date
	 * @param createDate  the value for sys_dict.create_date
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.update_by
	 * @return  the value of sys_dict.update_by
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.update_by
	 * @param updateBy  the value for sys_dict.update_by
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.update_date
	 * @return  the value of sys_dict.update_date
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.update_date
	 * @param updateDate  the value for sys_dict.update_date
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.remarks
	 * @return  the value of sys_dict.remarks
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.remarks
	 * @param remarks  the value for sys_dict.remarks
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.del_flag
	 * @return  the value of sys_dict.del_flag
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public String getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.del_flag
	 * @param delFlag  the value for sys_dict.del_flag
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.use_position
	 * @return  the value of sys_dict.use_position
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public String getUsePosition() {
		return usePosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.use_position
	 * @param usePosition  the value for sys_dict.use_position
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public void setUsePosition(String usePosition) {
		this.usePosition = usePosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.parent_id
	 * @return  the value of sys_dict.parent_id
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.parent_id
	 * @param parentId  the value for sys_dict.parent_id
	 * @mbggenerated  Sun Feb 19 21:43:19 CST 2017
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}
}