package com.gafker.manage.pojo;

public class Userpermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpermission.id
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpermission.permission_name
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpermission.Idx
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    private Integer idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpermission.WebUrls
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    private String weburls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpermission.AdsIds_fk
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    private String adsidsFk;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpermission.id
     *
     * @return the value of userpermission.id
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpermission.id
     *
     * @param id the value for userpermission.id
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpermission.permission_name
     *
     * @return the value of userpermission.permission_name
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpermission.permission_name
     *
     * @param permissionName the value for userpermission.permission_name
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpermission.Idx
     *
     * @return the value of userpermission.Idx
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpermission.Idx
     *
     * @param idx the value for userpermission.Idx
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpermission.WebUrls
     *
     * @return the value of userpermission.WebUrls
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public String getWeburls() {
        return weburls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpermission.WebUrls
     *
     * @param weburls the value for userpermission.WebUrls
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public void setWeburls(String weburls) {
        this.weburls = weburls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpermission.AdsIds_fk
     *
     * @return the value of userpermission.AdsIds_fk
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public String getAdsidsFk() {
        return adsidsFk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpermission.AdsIds_fk
     *
     * @param adsidsFk the value for userpermission.AdsIds_fk
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public void setAdsidsFk(String adsidsFk) {
        this.adsidsFk = adsidsFk;
    }
}