package com.gafker.manage.pojo;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotBlank;
import org.springframework.format.annotation.DateTimeFormat;
import com.gafker.manage.format.FormatExchangeAbstract;

public class Userattribute extends FormatExchangeAbstract implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 793018230123283039L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.Id
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.AccountIds_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private Integer accountidsFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.PhoneNum
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String phonenum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.FamilyNames_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private Long familynamesFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.UserName
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	@NotNull(message="{user.username.notnull}")
    //@Pattern(regexp="^[a-zA-Z0-9]+$",message="{account.username.space}")
	@Size(min=2,max=15,message="{user.username.length}")
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.Password
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	@NotBlank(message="{user.password.notnull}")
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.PswSalt
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String pswsalt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.PswSeq
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String pswseq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.WeChat
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String wechat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.AliPay
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String alipay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.Group1
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String group1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.Group2
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String group2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.Group3
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String group3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.HeadImage
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String headimage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.UserDetails
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String userdetails;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.CreateTime
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	@DateTimeFormat(pattern="yyyy/MM/dd")
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.UpdateTime
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	@DateTimeFormat(pattern="yyyy/MM/dd")
	private Date updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.UserQrcode
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String userqrcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.PointCount
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private Double pointcount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.MoneyCount
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private Double moneycount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.OtherCountObj
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String othercountobj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.VipLevel
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String viplevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.AdsIds_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private Integer adsidsFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.PublicActivityIds_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private Integer publicactivityidsFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.FamilyId_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private Long familyidFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.Clothespress_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private Long clothespressFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.FamilyGeneration_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private Long familygenerationFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.FamilyGeo_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private Long familygeoFk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.RelativesIds
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String relativesids;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.FriendIds
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String friendids;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.AttentionIds
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String attentionids;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.ProductIds
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String productids;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.ShowStatus
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private Integer showstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.RegCode
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	@NotBlank(message="请输入正确验证码")
	private String regcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.QrCode
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String qrcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.UserDesc
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private String userdesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.BirthdayDate
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	@DateTimeFormat(pattern="yyyy/MM/dd")
	private Date birthdaydate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.BirthdayCal
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private Integer birthdaycal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.Star
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private Double star;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattribute.DelFlag
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	private Integer delflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.Id
	 * @return  the value of userattribute.Id
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.Id
	 * @param id  the value for userattribute.Id
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.AccountIds_fk
	 * @return  the value of userattribute.AccountIds_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public Integer getAccountidsFk() {
		return accountidsFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.AccountIds_fk
	 * @param accountidsFk  the value for userattribute.AccountIds_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setAccountidsFk(Integer accountidsFk) {
		this.accountidsFk = accountidsFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.PhoneNum
	 * @return  the value of userattribute.PhoneNum
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getPhonenum() {
		return phonenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.PhoneNum
	 * @param phonenum  the value for userattribute.PhoneNum
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setPhonenum(String phonenum) {
		this.phonenum = phonenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.FamilyNames_fk
	 * @return  the value of userattribute.FamilyNames_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public Long getFamilynamesFk() {
		return familynamesFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.FamilyNames_fk
	 * @param familynamesFk  the value for userattribute.FamilyNames_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setFamilynamesFk(Long familynamesFk) {
		this.familynamesFk = familynamesFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.UserName
	 * @return  the value of userattribute.UserName
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.UserName
	 * @param username  the value for userattribute.UserName
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.Password
	 * @return  the value of userattribute.Password
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.Password
	 * @param password  the value for userattribute.Password
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.PswSalt
	 * @return  the value of userattribute.PswSalt
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getPswsalt() {
		return pswsalt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.PswSalt
	 * @param pswsalt  the value for userattribute.PswSalt
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setPswsalt(String pswsalt) {
		this.pswsalt = pswsalt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.PswSeq
	 * @return  the value of userattribute.PswSeq
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getPswseq() {
		return pswseq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.PswSeq
	 * @param pswseq  the value for userattribute.PswSeq
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setPswseq(String pswseq) {
		this.pswseq = pswseq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.WeChat
	 * @return  the value of userattribute.WeChat
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getWechat() {
		return wechat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.WeChat
	 * @param wechat  the value for userattribute.WeChat
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setWechat(String wechat) {
		this.wechat = wechat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.AliPay
	 * @return  the value of userattribute.AliPay
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getAlipay() {
		return alipay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.AliPay
	 * @param alipay  the value for userattribute.AliPay
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setAlipay(String alipay) {
		this.alipay = alipay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.Group1
	 * @return  the value of userattribute.Group1
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getGroup1() {
		return group1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.Group1
	 * @param group1  the value for userattribute.Group1
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setGroup1(String group1) {
		this.group1 = group1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.Group2
	 * @return  the value of userattribute.Group2
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getGroup2() {
		return group2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.Group2
	 * @param group2  the value for userattribute.Group2
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setGroup2(String group2) {
		this.group2 = group2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.Group3
	 * @return  the value of userattribute.Group3
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getGroup3() {
		return group3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.Group3
	 * @param group3  the value for userattribute.Group3
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setGroup3(String group3) {
		this.group3 = group3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.HeadImage
	 * @return  the value of userattribute.HeadImage
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getHeadimage() {
		return headimage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.HeadImage
	 * @param headimage  the value for userattribute.HeadImage
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setHeadimage(String headimage) {
		this.headimage = headimage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.UserDetails
	 * @return  the value of userattribute.UserDetails
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getUserdetails() {
		return userdetails;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.UserDetails
	 * @param userdetails  the value for userattribute.UserDetails
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setUserdetails(String userdetails) {
		this.userdetails = userdetails;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.CreateTime
	 * @return  the value of userattribute.CreateTime
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.CreateTime
	 * @param createtime  the value for userattribute.CreateTime
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.UpdateTime
	 * @return  the value of userattribute.UpdateTime
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.UpdateTime
	 * @param updatetime  the value for userattribute.UpdateTime
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.UserQrcode
	 * @return  the value of userattribute.UserQrcode
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getUserqrcode() {
		return userqrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.UserQrcode
	 * @param userqrcode  the value for userattribute.UserQrcode
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setUserqrcode(String userqrcode) {
		this.userqrcode = userqrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.PointCount
	 * @return  the value of userattribute.PointCount
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public Double getPointcount() {
		return pointcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.PointCount
	 * @param pointcount  the value for userattribute.PointCount
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setPointcount(Double pointcount) {
		this.pointcount = pointcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.MoneyCount
	 * @return  the value of userattribute.MoneyCount
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public Double getMoneycount() {
		return moneycount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.MoneyCount
	 * @param moneycount  the value for userattribute.MoneyCount
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setMoneycount(Double moneycount) {
		this.moneycount = moneycount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.OtherCountObj
	 * @return  the value of userattribute.OtherCountObj
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getOthercountobj() {
		return othercountobj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.OtherCountObj
	 * @param othercountobj  the value for userattribute.OtherCountObj
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setOthercountobj(String othercountobj) {
		this.othercountobj = othercountobj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.VipLevel
	 * @return  the value of userattribute.VipLevel
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getViplevel() {
		return viplevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.VipLevel
	 * @param viplevel  the value for userattribute.VipLevel
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setViplevel(String viplevel) {
		this.viplevel = viplevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.AdsIds_fk
	 * @return  the value of userattribute.AdsIds_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public Integer getAdsidsFk() {
		return adsidsFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.AdsIds_fk
	 * @param adsidsFk  the value for userattribute.AdsIds_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setAdsidsFk(Integer adsidsFk) {
		this.adsidsFk = adsidsFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.PublicActivityIds_fk
	 * @return  the value of userattribute.PublicActivityIds_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public Integer getPublicactivityidsFk() {
		return publicactivityidsFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.PublicActivityIds_fk
	 * @param publicactivityidsFk  the value for userattribute.PublicActivityIds_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setPublicactivityidsFk(Integer publicactivityidsFk) {
		this.publicactivityidsFk = publicactivityidsFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.FamilyId_fk
	 * @return  the value of userattribute.FamilyId_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public Long getFamilyidFk() {
		return familyidFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.FamilyId_fk
	 * @param familyidFk  the value for userattribute.FamilyId_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setFamilyidFk(Long familyidFk) {
		this.familyidFk = familyidFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.Clothespress_fk
	 * @return  the value of userattribute.Clothespress_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public Long getClothespressFk() {
		return clothespressFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.Clothespress_fk
	 * @param clothespressFk  the value for userattribute.Clothespress_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setClothespressFk(Long clothespressFk) {
		this.clothespressFk = clothespressFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.FamilyGeneration_fk
	 * @return  the value of userattribute.FamilyGeneration_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public Long getFamilygenerationFk() {
		return familygenerationFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.FamilyGeneration_fk
	 * @param familygenerationFk  the value for userattribute.FamilyGeneration_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setFamilygenerationFk(Long familygenerationFk) {
		this.familygenerationFk = familygenerationFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.FamilyGeo_fk
	 * @return  the value of userattribute.FamilyGeo_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public Long getFamilygeoFk() {
		return familygeoFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.FamilyGeo_fk
	 * @param familygeoFk  the value for userattribute.FamilyGeo_fk
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setFamilygeoFk(Long familygeoFk) {
		this.familygeoFk = familygeoFk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.RelativesIds
	 * @return  the value of userattribute.RelativesIds
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getRelativesids() {
		return relativesids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.RelativesIds
	 * @param relativesids  the value for userattribute.RelativesIds
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setRelativesids(String relativesids) {
		this.relativesids = relativesids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.FriendIds
	 * @return  the value of userattribute.FriendIds
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getFriendids() {
		return friendids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.FriendIds
	 * @param friendids  the value for userattribute.FriendIds
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setFriendids(String friendids) {
		this.friendids = friendids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.AttentionIds
	 * @return  the value of userattribute.AttentionIds
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getAttentionids() {
		return attentionids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.AttentionIds
	 * @param attentionids  the value for userattribute.AttentionIds
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setAttentionids(String attentionids) {
		this.attentionids = attentionids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.ProductIds
	 * @return  the value of userattribute.ProductIds
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getProductids() {
		return productids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.ProductIds
	 * @param productids  the value for userattribute.ProductIds
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setProductids(String productids) {
		this.productids = productids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.ShowStatus
	 * @return  the value of userattribute.ShowStatus
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public Integer getShowstatus() {
		return showstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.ShowStatus
	 * @param showstatus  the value for userattribute.ShowStatus
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setShowstatus(Integer showstatus) {
		this.showstatus = showstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.RegCode
	 * @return  the value of userattribute.RegCode
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getRegcode() {
		return regcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.RegCode
	 * @param regcode  the value for userattribute.RegCode
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setRegcode(String regcode) {
		this.regcode = regcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.QrCode
	 * @return  the value of userattribute.QrCode
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getQrcode() {
		return qrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.QrCode
	 * @param qrcode  the value for userattribute.QrCode
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setQrcode(String qrcode) {
		this.qrcode = qrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.UserDesc
	 * @return  the value of userattribute.UserDesc
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public String getUserdesc() {
		return userdesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.UserDesc
	 * @param userdesc  the value for userattribute.UserDesc
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setUserdesc(String userdesc) {
		this.userdesc = userdesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.BirthdayDate
	 * @return  the value of userattribute.BirthdayDate
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public Date getBirthdaydate() {
		return birthdaydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.BirthdayDate
	 * @param birthdaydate  the value for userattribute.BirthdayDate
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setBirthdaydate(Date birthdaydate) {
		this.birthdaydate = birthdaydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.BirthdayCal
	 * @return  the value of userattribute.BirthdayCal
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public Integer getBirthdaycal() {
		return birthdaycal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.BirthdayCal
	 * @param birthdaycal  the value for userattribute.BirthdayCal
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setBirthdaycal(Integer birthdaycal) {
		this.birthdaycal = birthdaycal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.Star
	 * @return  the value of userattribute.Star
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public Double getStar() {
		return star;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.Star
	 * @param star  the value for userattribute.Star
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setStar(Double star) {
		this.star = star;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattribute.DelFlag
	 * @return  the value of userattribute.DelFlag
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public Integer getDelflag() {
		return delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattribute.DelFlag
	 * @param delflag  the value for userattribute.DelFlag
	 * @mbggenerated  Tue Feb 28 02:16:11 CST 2017
	 */
	public void setDelflag(Integer delflag) {
		this.delflag = delflag;
	}

	@Override
	public String toJsonString(Userattribute entity) {
		if (entity != null) {
			return super.toJsonString(entity);
		}
		return super.toJsonString(this);
	}

	@Override
	public String toString() {
		return "Userattribute [id=" + id + ", accountidsFk=" + accountidsFk + ", phonenum=" + phonenum
				+ ", familynamesFk=" + familynamesFk + ", username=" + username + ", password=" + password
				+ ", pswsalt=" + pswsalt + ", pswseq=" + pswseq + ", wechat=" + wechat + ", alipay=" + alipay
				+ ", group1=" + group1 + ", group2=" + group2 + ", group3=" + group3 + ", headimage=" + headimage
				+ ", userdetails=" + userdetails + ", createtime=" + createtime + ", updatetime=" + updatetime
				+ ", userqrcode=" + userqrcode + ", pointcount=" + pointcount + ", moneycount=" + moneycount
				+ ", othercountobj=" + othercountobj + ", viplevel=" + viplevel + ", adsidsFk=" + adsidsFk
				+ ", publicactivityidsFk=" + publicactivityidsFk + ", familyidFk=" + familyidFk + ", clothespressFk="
				+ clothespressFk + ", familygenerationFk=" + familygenerationFk + ", familygeoFk=" + familygeoFk
				+ ", relativesids=" + relativesids + ", friendids=" + friendids + ", attentionids=" + attentionids
				+ ", productids=" + productids + ", showstatus=" + showstatus + ", regcode=" + regcode + ", qrcode="
				+ qrcode + ", userdesc=" + userdesc + ", birthdaydate=" + birthdaydate + ", birthdaycal=" + birthdaycal
				+ ", star=" + star + ", delflag=" + delflag + "]";
	}
	
	
}