package com.gafker.manage.pojo;

public class Userfkrole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfkrole.id
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfkrole.user_id
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfkrole.role_id
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfkrole.Idx
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    private Integer idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfkrole.WebUrls
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    private String weburls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfkrole.AdsIds_fk
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    private String adsidsFk;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfkrole.id
     *
     * @return the value of userfkrole.id
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfkrole.id
     *
     * @param id the value for userfkrole.id
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfkrole.user_id
     *
     * @return the value of userfkrole.user_id
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfkrole.user_id
     *
     * @param userId the value for userfkrole.user_id
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfkrole.role_id
     *
     * @return the value of userfkrole.role_id
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfkrole.role_id
     *
     * @param roleId the value for userfkrole.role_id
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfkrole.Idx
     *
     * @return the value of userfkrole.Idx
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfkrole.Idx
     *
     * @param idx the value for userfkrole.Idx
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfkrole.WebUrls
     *
     * @return the value of userfkrole.WebUrls
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public String getWeburls() {
        return weburls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfkrole.WebUrls
     *
     * @param weburls the value for userfkrole.WebUrls
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public void setWeburls(String weburls) {
        this.weburls = weburls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfkrole.AdsIds_fk
     *
     * @return the value of userfkrole.AdsIds_fk
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public String getAdsidsFk() {
        return adsidsFk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfkrole.AdsIds_fk
     *
     * @param adsidsFk the value for userfkrole.AdsIds_fk
     *
     * @mbggenerated Mon Feb 20 08:46:09 CST 2017
     */
    public void setAdsidsFk(String adsidsFk) {
        this.adsidsFk = adsidsFk;
    }
}