package com.gafker.manage.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.gafker.manage.entity.Familygeo;
import com.gafker.manage.entity.FamilygeoExample;

public interface FamilygeoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familygeo
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int countByExample(FamilygeoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familygeo
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int deleteByExample(FamilygeoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familygeo
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familygeo
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int insert(Familygeo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familygeo
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int insertSelective(Familygeo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familygeo
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	List<Familygeo> selectByExample(FamilygeoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familygeo
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	Familygeo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familygeo
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Familygeo record, @Param("example") FamilygeoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familygeo
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int updateByExample(@Param("record") Familygeo record, @Param("example") FamilygeoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familygeo
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int updateByPrimaryKeySelective(Familygeo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familygeo
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int updateByPrimaryKey(Familygeo record);
}