package com.gafker.manage.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.gafker.manage.pojo.Familytraceability;
import com.gafker.manage.pojo.FamilytraceabilityExample;

public interface FamilytraceabilityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int countByExample(FamilytraceabilityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int deleteByExample(FamilytraceabilityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int insert(Familytraceability record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int insertSelective(Familytraceability record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	List<Familytraceability> selectByExample(FamilytraceabilityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	Familytraceability selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Familytraceability record,
			@Param("example") FamilytraceabilityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int updateByExample(@Param("record") Familytraceability record,
			@Param("example") FamilytraceabilityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int updateByPrimaryKeySelective(Familytraceability record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familytraceability
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int updateByPrimaryKey(Familytraceability record);
}