package com.gafker.manage.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.gafker.manage.entity.Familyclothespress;
import com.gafker.manage.entity.FamilyclothespressExample;

public interface FamilyclothespressMapper{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyclothespress
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int countByExample(FamilyclothespressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyclothespress
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int deleteByExample(FamilyclothespressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyclothespress
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyclothespress
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int insert(Familyclothespress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyclothespress
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int insertSelective(Familyclothespress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyclothespress
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	List<Familyclothespress> selectByExample(FamilyclothespressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyclothespress
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	Familyclothespress selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyclothespress
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Familyclothespress record,
			@Param("example") FamilyclothespressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyclothespress
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int updateByExample(@Param("record") Familyclothespress record,
			@Param("example") FamilyclothespressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyclothespress
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int updateByPrimaryKeySelective(Familyclothespress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table familyclothespress
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int updateByPrimaryKey(Familyclothespress record);
}