package com.gafker.manage.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.gafker.manage.pojo.Familyphoto;
import com.gafker.manage.pojo.FamilyphotoExample;

public interface FamilyphotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyphoto
     *
     * @mbggenerated Sat Mar 11 21:42:03 CST 2017
     */
    int countByExample(FamilyphotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyphoto
     *
     * @mbggenerated Sat Mar 11 21:42:03 CST 2017
     */
    int deleteByExample(FamilyphotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyphoto
     *
     * @mbggenerated Sat Mar 11 21:42:03 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyphoto
     *
     * @mbggenerated Sat Mar 11 21:42:03 CST 2017
     */
    int insert(Familyphoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyphoto
     *
     * @mbggenerated Sat Mar 11 21:42:03 CST 2017
     */
    int insertSelective(Familyphoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyphoto
     *
     * @mbggenerated Sat Mar 11 21:42:03 CST 2017
     */
    List<Familyphoto> selectByExample(FamilyphotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyphoto
     *
     * @mbggenerated Sat Mar 11 21:42:03 CST 2017
     */
    Familyphoto selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyphoto
     *
     * @mbggenerated Sat Mar 11 21:42:03 CST 2017
     */
    int updateByExampleSelective(@Param("record") Familyphoto record, @Param("example") FamilyphotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyphoto
     *
     * @mbggenerated Sat Mar 11 21:42:03 CST 2017
     */
    int updateByExample(@Param("record") Familyphoto record, @Param("example") FamilyphotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyphoto
     *
     * @mbggenerated Sat Mar 11 21:42:03 CST 2017
     */
    int updateByPrimaryKeySelective(Familyphoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table familyphoto
     *
     * @mbggenerated Sat Mar 11 21:42:03 CST 2017
     */
    int updateByPrimaryKey(Familyphoto record);
}