package com.gafker.manage.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.gafker.manage.entity.Happayteachersdays;
import com.gafker.manage.entity.HappayteachersdaysExample;
import com.gafker.manage.entity.Page;

public interface HappayteachersdaysMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table happayteachersdays
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int countByExample(HappayteachersdaysExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table happayteachersdays
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int deleteByExample(HappayteachersdaysExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table happayteachersdays
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int deleteByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table happayteachersdays
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int insert(Happayteachersdays record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table happayteachersdays
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int insertSelective(Happayteachersdays record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table happayteachersdays
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	List<Happayteachersdays> selectByExample(HappayteachersdaysExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table happayteachersdays
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	Happayteachersdays selectByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table happayteachersdays
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Happayteachersdays record,
			@Param("example") HappayteachersdaysExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table happayteachersdays
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int updateByExample(@Param("record") Happayteachersdays record,
			@Param("example") HappayteachersdaysExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table happayteachersdays
	 * @rmbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int updateByPrimaryKeySelective(Happayteachersdays record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table happayteachersdays
	 * @mbggenerated  Sun Feb 19 19:50:51 CST 2017
	 */
	int updateByPrimaryKey(Happayteachersdays record);
	/**
     * Gafker no page
     * @return
     */
    List<Happayteachersdays> selectAll();
    /**
     * Gafker  page
     * @return
     */
    List<Happayteachersdays> selectPage(Page<?> page);
}