package com.gafker.manage.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.gafker.manage.entity.SysDictType;
import com.gafker.manage.entity.SysDictTypeExample;

public interface SysDictTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_type
	 * @mbg.generated  Thu Apr 06 15:25:15 CST 2017
	 */
	long countByExample(SysDictTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_type
	 * @mbg.generated  Thu Apr 06 15:25:15 CST 2017
	 */
	int deleteByExample(SysDictTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_type
	 * @mbg.generated  Thu Apr 06 15:25:15 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_type
	 * @mbg.generated  Thu Apr 06 15:25:15 CST 2017
	 */
	int insert(SysDictType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_type
	 * @mbg.generated  Thu Apr 06 15:25:15 CST 2017
	 */
	int insertSelective(SysDictType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_type
	 * @mbg.generated  Thu Apr 06 15:25:15 CST 2017
	 */
	List<SysDictType> selectByExample(SysDictTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_type
	 * @mbg.generated  Thu Apr 06 15:25:15 CST 2017
	 */
	SysDictType selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_type
	 * @mbg.generated  Thu Apr 06 15:25:15 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysDictType record, @Param("example") SysDictTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_type
	 * @mbg.generated  Thu Apr 06 15:25:15 CST 2017
	 */
	int updateByExample(@Param("record") SysDictType record, @Param("example") SysDictTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_type
	 * @mbg.generated  Thu Apr 06 15:25:15 CST 2017
	 */
	int updateByPrimaryKeySelective(SysDictType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_type
	 * @mbg.generated  Thu Apr 06 15:25:15 CST 2017
	 */
	int updateByPrimaryKey(SysDictType record);
}