package com.gafker.manage.mapper;

import com.gafker.manage.pojo.SysShoesSize;
import com.gafker.manage.pojo.SysShoesSizeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysShoesSizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_shoes_size
     *
     * @mbg.generated Thu Apr 13 21:39:08 CST 2017
     */
    long countByExample(SysShoesSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_shoes_size
     *
     * @mbg.generated Thu Apr 13 21:39:08 CST 2017
     */
    int deleteByExample(SysShoesSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_shoes_size
     *
     * @mbg.generated Thu Apr 13 21:39:08 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_shoes_size
     *
     * @mbg.generated Thu Apr 13 21:39:08 CST 2017
     */
    int insert(SysShoesSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_shoes_size
     *
     * @mbg.generated Thu Apr 13 21:39:08 CST 2017
     */
    int insertSelective(SysShoesSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_shoes_size
     *
     * @mbg.generated Thu Apr 13 21:39:08 CST 2017
     */
    List<SysShoesSize> selectByExample(SysShoesSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_shoes_size
     *
     * @mbg.generated Thu Apr 13 21:39:08 CST 2017
     */
    SysShoesSize selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_shoes_size
     *
     * @mbg.generated Thu Apr 13 21:39:08 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysShoesSize record, @Param("example") SysShoesSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_shoes_size
     *
     * @mbg.generated Thu Apr 13 21:39:08 CST 2017
     */
    int updateByExample(@Param("record") SysShoesSize record, @Param("example") SysShoesSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_shoes_size
     *
     * @mbg.generated Thu Apr 13 21:39:08 CST 2017
     */
    int updateByPrimaryKeySelective(SysShoesSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_shoes_size
     *
     * @mbg.generated Thu Apr 13 21:39:08 CST 2017
     */
    int updateByPrimaryKey(SysShoesSize record);
}