package com.gafker.manage.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.gafker.manage.pojo.Visitorcount;
import com.gafker.manage.pojo.VisitorcountExample;

public interface VisitorcountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorcount
     *
     * @mbggenerated Sat Sep 17 07:08:02 CST 2016
     */
    int countByExample(VisitorcountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorcount
     *
     * @mbggenerated Sat Sep 17 07:08:02 CST 2016
     */
    int deleteByExample(VisitorcountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorcount
     *
     * @mbggenerated Sat Sep 17 07:08:02 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorcount
     *
     * @mbggenerated Sat Sep 17 07:08:02 CST 2016
     */
    int insert(Visitorcount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorcount
     *
     * @mbggenerated Sat Sep 17 07:08:02 CST 2016
     */
    int insertSelective(Visitorcount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorcount
     *
     * @mbggenerated Sat Sep 17 07:08:02 CST 2016
     */
    List<Visitorcount> selectByExample(VisitorcountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorcount
     *
     * @mbggenerated Sat Sep 17 07:08:02 CST 2016
     */
    Visitorcount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorcount
     *
     * @mbggenerated Sat Sep 17 07:08:02 CST 2016
     */
    int updateByExampleSelective(@Param("record") Visitorcount record, @Param("example") VisitorcountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorcount
     *
     * @mbggenerated Sat Sep 17 07:08:02 CST 2016
     */
    int updateByExample(@Param("record") Visitorcount record, @Param("example") VisitorcountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorcount
     *
     * @mbggenerated Sat Sep 17 07:08:02 CST 2016
     */
    int updateByPrimaryKeySelective(Visitorcount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitorcount
     *
     * @mbggenerated Sat Sep 17 07:08:02 CST 2016
     */
    int updateByPrimaryKey(Visitorcount record);
}